---
# Commented out content is serving as example for you to add new content.
tower_inventories:
  - name: localhost
    description: inventory for localhost
    organization: Satellite
  - name: satlab-admin-inventory
    description: Load inventory from satlab-admin hosts file
    organization: Satellite
  - name: RHVM-01
    organization: Satellite
    description: created by Ansible Playbook - for RHVM-01
  - name: RHVM-02
    organization: Satellite
    description: created by Ansible Playbook - for RHVM-02
  - name: Test Inventory - Smart
    organization: Default
    description: created by Ansible Playbook
    kind: smart
    host_filter:  "name__icontains=localhost"
