---
tower_inventory_sources:
  - name: RHVM-01
    source: rhv
    inventory: RHVM-01
    credential: admin@internal-RHVM-01
    description: created by Ansible Tower
    overwrite: true
    update_on_launch: true
    update_cache_timeout: 0
    # more options can be provided but for RHV source we are using, we need only this much.
