---
# Commented out content is serving as example for you to add new content.
tower_credentials:
  - kind: ssh
    name: Demo Credential
    inputs:
      username: username
    organization: Default
  - kind: rhv
    name: admin@internal-RHVM-01
    description: infra-rhvm-01 creds for inventory sources.
    inputs:
      host: "https://example.com/ovirt-engine/api"
      username: "user"
      password: "password"
    organization: Satellite
  - kind: ssh
    organization: Satellite
    name: machine-creds-with-jenkins-pvt-key
    description: This credential can be used with any vm that contains jenkins_public key in authorized keys
    inputs:
      username: root
      ssh_key_data: "{{ ssh_private_key }}"
  - kind: scm
    name: gitlab-personal-access-token for satqe_auto_droid
    description: General purpose token that can be used by anyone for satlab-admin(or other private) repo clone
    inputs:
      username: gitlab
      password: password
    organization: Satellite
  - kind: vault
    name: satlab-admin-vault
    inputs:
      vault_password: s3cr3t
    description: satlab-admin-vault password aka vault_secret
    organization: Satellite
  - description: CyberArk Lookup Credential
    name: "cyberark"
    credential_type: CyberArk AIM Central Credential Provider Lookup
    inputs:
      url: "https://cyberark.example.com"
      app_id: "My-App-ID"
    organization: Default
  - kind: scm
    name: gitlab
    organization: Default
    inputs:
      username: username
