---
tower_hosts:
  - name: localhost
    inventory: localhost
    variables:
      some_var: some_val
      ansible_connection: local
  - name: PSQL1
    inventory: satlab-admin-inventory
    variables:
      some_var: some_val
      ansible_connection: local
  - name: PSQL2
    inventory: satlab-admin-inventory
    variables:
      some_var: some_val
      ansible_connection: local
  - name: PSQL3
    inventory: satlab-admin-inventory
    variables:
      some_var: some_val
      ansible_connection: local
