---
- name: private_automation_hub | Create DNS record
  become: false
  community.aws.route53:
    state: "{{ s3_state }}"
    zone: "{{ workshop_dns_zone }}"
    record: "hub.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    type: A
    overwrite: true
    value: "{{ ansible_host }}"
    wait: false
  delegate_to: localhost
  register: route53_status
