---
- name: git pre | check to see if SSL cert already applied
  become: false
  get_certificate:
    host: "gitlab.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    port: 443
  delegate_to: localhost
  run_once: true
  failed_when: false
  register: check_cert

- block:
    - name: git pre | Install required RPM GPG keys
      rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
      become: true

    - name: git pre | Install EPEL
      dnf:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
        state: present

    # temporary fix for rhel 8.2 dnf substitution
    - name: git pre | fix EPEL repo substitution
      replace:
        path: "{{ item }}"
        regexp: '\$releasever'
        replace: '8'
      loop:
        - /etc/yum.repos.d/epel-modular.repo
        - /etc/yum.repos.d/epel.repo
      when:
        - ansible_distribution_major_version|int == 8

    - name: git pre | Install base packages
      dnf:
        name:
          - python3-pip
          - python3-devel
          - certbot
        disable_gpg_check: true

    - name: git pre | get some certs
      block:
        - name: git pre | issue cert
          shell: certbot certonly --no-bootstrap --standalone -d gitlab.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}} --email ansible-network@redhat.com --noninteractive --agree-tos
          register: issue_gitlab_cert
          until: issue_gitlab_cert is not failed
          retries: 5

        # this is used because gitea runs as non-root and needs access to the certs
        # TODO: fix add conditional for gitea or gitlab
        - name: git pre | set permissions on cert
          shell: chmod -R 0755 /etc/letsencrypt/{live,archive}
          become: true

        - name: git pre | use self signed cert
          set_fact:
            gitlab_create_self_signed_cert: false
            gitlab_ssl_certificate: "/etc/letsencrypt/live/gitlab.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}/fullchain.pem"
            gitlab_ssl_certificate_key: "/etc/letsencrypt/live/gitlab.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}/privkey.pem"
      rescue:
        - name: git pre | use self signed cert
          set_fact:
            gitlab_create_self_signed_cert: true

  when: check_cert.cert is not defined
