---
- name: grab facts for node7 node
  ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop_node7": "{{ec2_name_prefix}}-node7"
  register: node7_node_facts

- name: grab facts for node8 node
  ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop_node8": "{{ec2_name_prefix}}-node8"
  register: node8_node_facts

- name: grab facts for node9 node
  ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop_node9": "{{ec2_name_prefix}}-node9"
  register: node9_node_facts

- name: add hosts to groups (ANSIBLE RHEL MODE)
  add_host:
    name: "{{ item.tags.Name }}"
    username: "{{ item.tags.Student }}"
    short_name: "{{ item.tags.short_name }}"
    ansible_host: "{{ item.public_ip_address }}"
    ansible_user: "{{ item.tags.username }}"
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    groups: lab_hosts,managed_nodes
  with_items:
    - "{{ node7_node_facts.instances }}"
    - "{{ node8_node_facts.instances }}"
    - "{{ node9_node_facts.instances }}"
  changed_when: false
