---
controller_hosts:
  - name: "backup-server"
    description: "this server is where we backup network configuration"
    inventory: "Workshop Inventory"
    enabled: true
    variables:
      note: in production these passwords would be encrypted in vault
      ansible_user: "ec2-user"
      ansible_password: "{{ admin_password }}"
      ansible_host: "{{ ansible_host }}"
  - name: "ansible-1"
    description: "control node where AAP is running"
    inventory: "Workshop Inventory"
    enabled: true
    variables:
      ansible_user: "ec2-user"
aap_organizations:
  - name: "Red Hat network organization"
    description: "Red Hat Network Organization"
    galaxy_credentials:
      - "Ansible Galaxy"
  - name: "Red Hat compute organization"
    description: "Red Hat Compute Organization"
    galaxy_credentials:
      - "Ansible Galaxy"
aap_teams:
  - name: "Netops"
    description: "Network Ops Team"
    organization: "Red Hat network organization"
  - name: "Netadmin"
    description: "Network Admin Team"
    organization: "Red Hat network organization"
  - name: "Compute T1"
    description: "Computer T1 Team"
    organization: "Red Hat compute organization"
  - name: "Compute T2"
    description: "Computer T2 Team"
    organization: "Red Hat compute organization"
aap_user_accounts:
  - username: network-operator
    is_superuser: false
    password: "{{ admin_password }}"
    email: nwops@redhat.com
    first_name: Issac
    last_name: Assimov
  - username: network-admin
    is_superuser: false
    password: "{{ admin_password }}"
    email: nwadmin@redhat.com
    first_name: Larry
    last_name: Niven
  - username: bbelcher
    is_superuser: true
    password: "{{ admin_password }}"
    email: bbelcher@redhat.com
    first_name: Bob
    last_name: Belcher
  - username: tbelcher
    password: "{{ admin_password }}"
    email: tbelcher@redhat.com
    first_name: Tina
    last_name: Belcher
  - username: lbelcher
    password: "{{ admin_password }}"
    email: lbelcher@redhat.com
    first_name: Louise
    last_name: Belcher
  - username: libelcher
    password: "{{ admin_password }}"
    email: libelcher@redhat.com
    first_name: Linda
    last_name: Belcher
  - username: gbelcher
    password: "{{ admin_password }}"
    email: gbelcher@redhat.com
    first_name: Gene
    last_name: Belcher
controller_projects:
  - name: "Workshop Project"
    organization: "Red Hat network organization"
    scm_type: git
    scm_url: "https://github.com/network-automation/toolkit"
gateway_role_user_assignments:
  - user: network-admin
    organization: "Red Hat network organization"
    role: member
  - user: network-admin
    organization: "Red Hat network organization"
    role: admin
  - user: network-operator
    organization: "Red Hat network organization"
    role: member
  - user: network-operator
    target_team: "Netops"
    role: member
  - role: use
    inventory: "Workshop Inventory"
    team: Netops
  - role: use
    inventory: "Workshop Inventory"
    team: Netadmin
  - user: network-operator
    role: execute
    job_template: "Network-Commands"
controller_templates:
  - name: "Network-Commands"
    description: "adhoc cisco commands"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "Workshop Project"
    playbook: "playbooks/network_commands.yml"
    credentials: "Workshop Credential"
    limit: "cisco"
    survey_enabled: true
    survey: "{{ lookup('template', 'survey_spec.json') }}"
    execution_environment: "network workshop execution environment"
  - name: "Network-Reload"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "Workshop Project"
    playbook: "playbooks/network_reload.yml"
    credentials: "Workshop Credential"
    execution_environment: "network workshop execution environment"
  - name: "Network-User"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "Workshop Project"
    playbook: "playbooks/network_user.yml"
    credentials: "Workshop Credential"
    state: "present"
    survey_enabled: true
    survey: "{{ lookup('template', 'user.json') }}"
    execution_environment: "network workshop execution environment"
  - name: "Network-Time"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "Workshop Project"
    playbook: "playbooks/network_time.yml"
    credentials: "Workshop Credential"
    limit: "cisco"
    survey_enabled: true
    survey: "{{ lookup('template', 'network_time.json') }}"
    execution_environment: "network workshop execution environment"
  - name: "Network-Report"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "Workshop Project"
    playbook: "playbooks/network_report.yml"
    credentials: "Workshop Credential"
    execution_environment: "network workshop execution environment"
  - name: "Network-System"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "Workshop Project"
    playbook: "playbooks/network_system.yml"
    credentials: "Workshop Credential"
    limit: "cisco"
    survey_enabled: true
    survey: "{{ lookup('template', 'system.json') }}"
    execution_environment: "network workshop execution environment"
controller_groups:
  - name: cisco
    inventory: "Workshop Inventory"
    variables:
      ansible_network_os: ios
      ansible_connection: network_cli
  - name: arista
    inventory: "Workshop Inventory"
    variables:
      ansible_network_os: eos
      ansible_connection: network_cli
      ansible_become: true
      ansible_become_method: enable
  - name: juniper
    inventory: "Workshop Inventory"
    variables:
      ansible_network_os: junos
      ansible_connection: netconf
