controller_projects:
  - name: "Ansible official demo project"
    scm_type: git
    scm_url: "https://github.com/ansible/product-demos"
    description: "prescriptive demos from Red Hat Management Business Unit"
    organization: "Default"

controller_templates:
  - name: "SECURITY / Hardening"
    description: "hardening for Linux servers"
    project: "Ansible official demo project"
    job_type: "run"
    inventory: "Workshop Inventory"
    playbook: "playbooks/security/hardening.yml"
    credential: "Workshop Credential"
    survey_enabled: true
    execution_environment: "Default execution environment"
    survey:
      name: Hardening survey
      description: Configure firewall, time, SSH and PCI baseline
      spec:
        - question_name: 'Enter host to configure'
          type: text
          variable: HOSTS
          required: false
        - question_name: Configure Firewall?
          type: multiplechoice
          variable: harden_firewall
          required: false
          choices:
            - 'Yes'
            - 'No'
        - question_name: Configure Time?
          type: multiplechoice
          variable: harden_time
          required: false
          choices:
            - 'Yes'
            - 'No'
        - question_name: Harden SSH?
          type: multiplechoice
          variable: harden_ssh
          required: false
          choices:
            - 'Yes'
            - 'No'
        - question_name: PCI Baseline?
          type: multiplechoice
          variable: harden_pci
          required: false
          choices:
            - 'Yes'
            - 'No'
