---
galaxy_info:
  role_name: redhat_cop.tower_utilities.kerberos
  author: "Andrew J. Huffman"
  description: "An Ansible role to configure Ansible Tower nodes to manage Windows systems."
  company: "Red Hat"

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: "MIT"

  min_ansible_version: "2.4"

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If travis integration is cofigured, only notification for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  # github_branch:

  #
  # Below are all platforms currently available. Just uncomment
  # the ones that apply to your role. If you don't see your
  # platform on this list, let us know and we'll get it added!
  #
  platforms:
    - name: "EL"
      versions:
        - "all"
        #   - 5
        #   - 6
        # - name: GenericUNIX
        #   versions:
        #   - all
        #   - any
        # - name: Solaris
        #   versions:
        #   - all
        #   - 10
        #   - 11.0
        #   - 11.1
        #   - 11.2
        #   - 11.3
        # - name: Fedora
        #   versions:
        #   - all
        #   - 16
        #   - 17
        #   - 18
        #   - 19
        #   - 20
        #   - 21
        #   - 22
        #   - 23
        # - name: opensuse
        #   versions:
        #   - all
        #   - 12.1
        #   - 12.2
        #   - 12.3
        #   - 13.1
        #   - 13.2
        # - name: IOS
        #   versions:
        #   - all
        #   - any
        # - name: SmartOS
        #   versions:
        #   - all
        #   - any
        # - name: eos
        #   versions:
        #   - all
        #   - Any
        # - name: Windows
        #   versions:
        #   - all
        #   - 2012R2
        # - name: Amazon
        #   versions:
        #   - all
        #   - 2013.03
        #   - 2013.09
        # - name: GenericBSD
        #   versions:
        #   - all
        #   - any
        # - name: Junos
        #   versions:
        #   - all
        #   - any
        # - name: FreeBSD
        #   versions:
        #   - all
        #   - 10.0
        #   - 10.1
        #   - 10.2
        #   - 8.0
        #   - 8.1
        #   - 8.2
        #   - 8.3
        #   - 8.4
        #   - 9.0
        #   - 9.1
        #   - 9.1
        #   - 9.2
        #   - 9.3
        # - name: Ubuntu
        #   versions:
        #   - all
        #   - lucid
        #   - maverick
        #   - natty
        #   - oneiric
        #   - precise
        #   - quantal
        #   - raring
        #   - saucy
        #   - trusty
        #   - utopic
        #   - vivid
        # - wily
        # - xenial
        # - name: SLES
        #   versions:
        #   - all
        #   - 10SP3
        #   - 10SP4
        #   - 11
        #   - 11SP1
        #   - 11SP2
        #   - 11SP3
        # - name: GenericLinux
        #   versions:
        #   - all
        #   - any
        # - name: NXOS
        #   versions:
        #   - all
        #   - any

  galaxy_tags:
    - "ansibletower"
    - "tower"
    - "awx"
    - "configuration"
    - "system"
    - "kerberos"
    - "pywinrm"
    - "winrm"
    # List tags for your role here, one per line. A tag is
    # a keyword that describes and categorizes the role.
    # Users find roles by searching for tags. Be sure to
    # remove the '[]' above if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of
    # alphanumeric characters. Maximum 20 tags per role.

dependencies: []
# List your role dependencies here, one per line.
# Be sure to remove the '[]' above if you add dependencies
# to this list.
