---
admin_password: ansible
code_server: true
workshop_dns_zone: "rhdemo.io"
s3_state: "present"
teardown: false
towerinstall: false
populatetower: true
website_information: ""
login_website_information: ""
dns_information: "No errors with DNS"
callback_information: "No issue with Ansible Tower callback"
workshop_type: ""
dns_type: aws
valid_dns_type:
  - aws
  - none
valid_workshop_types:
  - network
  - f5
  - rhel
  - devops
  - security
  - storage
  - windows
  - rhel_90
network_type: multivendor
valid_network_types:
  - cisco
  - arista
  - juniper
  - multivendor
doubleup: false
create_login_page: true
attendance: true
security_console: qradar
valid_security_console_types:
  - splunk
  - qradar
ibm_community_grid: true
