---
workshop_version: aug11-2022
student_user: student
admin_password: ansible
code_server: true
workshop_dns_zone: "rhdemo.io"
s3_state: "present"
teardown: false
controllerinstall: true
populatecontroller: true
website_information: ""
login_website_information: ""
dns_information: ""
callback_information: "No issue with Ansible Controller callback"
demo_information: "No errors with Demos"
workshop_type: ""
dns_type: aws
valid_dns_type:
  - aws
  - none
valid_workshop_types:
  - network
  - f5
  - rhel
  - devops
  - security
  - windows
  - rhel_90
  - demo
  - smart_mgmt
  - middleware
  - configascode
  - ripu
network_type: multivendor
valid_network_types:
  - cisco
  - arista
  - juniper
  - multivendor
doubleup: false
attendance: true
security_console: qradar
valid_security_console_types:
  - splunk
  - qradar
create_cluster: false
automation_hub: false
developer_mode: false
pre_build: true
agnosticd_callback_url: ""

# workshop execution environments
f5_ee: "quay.io/acme_corp/f5_ee:latest"
security_ee: "quay.io/acme_corp/security_ee:latest"
rhel_ee: "registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8:1.0.0-208"
network_ee: "quay.io/acme_corp/network-ee:latest"
rhel_90_ee: "quay.io/acme_corp/rhel_90_ee:latest"
windows_ee: "quay.io/acme_corp/windows_ee:latest"
smart_mgmt_ee: "quay.io/s4v0/ee-automated-smart-mgmt-29:latest"
configascode_ee: "registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:latest"
ripu_ee: "registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8:1.0.0-208"

# EE registry name used in installer and EE controller credential
ee_registry_name: "registry.redhat.io"

# List of execution environments to download during controller installation:
ee_images:
   - "{{ ee_registry_name }}/ansible-automation-platform-23/ee-29-rhel8:latest"
   - "{{ ee_registry_name }}/ansible-automation-platform-23/ee-supported-rhel8:latest"
   - "{{ ee_registry_name }}/ansible-automation-platform-23/ee-minimal-rhel8:latest"

# Default EE that uses the registry credential (Default execution environment)
ee_default_image: "{{ ee_registry_name }}/ansible-automation-platform-23/ee-supported-rhel8:latest"
