---
theme: jekyll-theme-dinky
include:
  - "provisioner/README.md"
exclude:
  - "roles"
  - "provisioner/roles"
  - "provisioner/group_vars"
  - "provisioner/inventory"
  - "provisioner/tests"
kramdown:
  syntax_highlighter_opts:
    disable: true
