---
theme: jekyll-theme-minimal
include:
  - "provisioner/README.md"
exclude:
  - "roles"
  - "provisioner/roles"
  - "provisioner/group_vars"
  - "provisioner/inventory"
  - "provisioner/tests"
  - "legacy-assets"
kramdown:
  syntax_highlighter_opts:
    disable: true
