---
- name: grab facts for node1 node
  ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop_node1": "{{ec2_name_prefix}}-node1"
  register: node1_node_facts

- name: grab facts for node2 node
  ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop_node2": "{{ec2_name_prefix}}-node2"
  register: node2_node_facts

- name: grab facts for node3 node
  ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop_node3": "{{ec2_name_prefix}}-node3"
  register: node3_node_facts

- name: grab facts for isonode
  ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop_isonode": "{{ec2_name_prefix}}-isonode"
  register: isonode_node_facts
  when: create_cluster|bool

- name: grab facts for remotenode node
  ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop_remotenode": "{{ec2_name_prefix}}-remotenode"
  register: remotenode_node_facts
  when: create_cluster|bool

- name: add hosts to groups (ANSIBLE RHEL MODE)
  add_host:
    name: "{{ item.tags.Name }}"
    username: "{{ item.tags.Student }}"
    short_name: "{{ item.tags.short_name }}"
    ansible_host: "{{ item.public_ip_address }}"
    ansible_user: "{{ item.tags.username }}"
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    groups: lab_hosts,managed_nodes
  with_items:
    - "{{ node1_node_facts.instances }}"
    - "{{ node2_node_facts.instances }}"
    - "{{ node3_node_facts.instances }}"
  changed_when: false

- name: add nodes for cluster lab to groups (ANSIBLE RHEL MODE)
  add_host:
    name: "{{ item.tags.Name }}"
    username: "{{ item.tags.Student }}"
    short_name: "{{ item.tags.short_name }}"
    ansible_host: "{{ item.public_ip_address }}"
    ansible_user: "{{ item.tags.username }}"
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    groups: lab_hosts,managed_nodes
  with_items:
    - "{{ isonode_node_facts.instances }}"
    - "{{ remotenode_node_facts.instances }}"
  # changed_when: false
  when: create_cluster|bool
