---
- name: grab facts for f5 node (F5 MODE)
  ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop_f5": "{{ec2_name_prefix}}-f5"
  register: f5_node_facts

- name: add f5 to groups (F5 MODE)
  add_host:
    name: "{{ item.tags.Name }}"
    short_name: "{{ item.tags.short_name }}"
    ansible_host: "{{ item.public_ip_address }}"
    ansible_user: admin
    ansible_password: admin
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    private_ip: "{{item.private_ip_address}}"
    groups:
      - f5
  with_items: "{{ f5_node_facts.instances }}"

- name: grab facts for node1 node (F5 MODE)
  ec2_instance_facts:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop_node1": "{{ec2_name_prefix}}-node1"
  register: f5_node1_node_facts

- name: add node1 to groups (F5 MODE)
  add_host:
    name: "{{ item.tags.Name }}"
    short_name: "{{ item.tags.short_name }}"
    username: "{{ item.tags.Student }}"
    ansible_host: "{{ item.public_ip_address }}"
    ansible_user: "{{ item.tags.username }}"
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    private_ip: "{{item.private_ip_address}}"
    groups:
      - lab_hosts
      - managed_nodes
  with_items: "{{ f5_node1_node_facts.instances }}"

- name: grab facts for node2 node (F5 MODE)
  ec2_instance_facts:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop_node2": "{{ec2_name_prefix}}-node2"
  register: f5_node2_node_facts

- name: add node2 to groups (F5 MODE)
  add_host:
    name: "{{ item.tags.Name }}"
    short_name: "{{ item.tags.short_name }}"
    username: "{{ item.tags.Student }}"
    ansible_host: "{{ item.public_ip_address }}"
    ansible_user: "{{ item.tags.username }}"
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    private_ip: "{{item.private_ip_address}}"
    groups:
      - lab_hosts
      - managed_nodes
  with_items: "{{ f5_node2_node_facts.instances }}"
