---
- name: grab facts for node1 - dev_web1
  ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop": "{{ec2_name_prefix}}"
      "tag:Devops_tag": "dev_web1"
  register: node1_node_facts

- name: grab facts for node2 node - dev_web2
  ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop": "{{ec2_name_prefix}}"
      "tag:Devops_tag": "dev_web2"
  register: node2_node_facts

- name: grab facts for node3 node - prod_web1
  ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop": "{{ec2_name_prefix}}"
      "tag:Devops_tag": "prod_web1"
  register: node3_node_facts

- name: grab facts for node4 node - prod_web2
  ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop": "{{ec2_name_prefix}}"
      "tag:Devops_tag": "prod_web2"
  register: node4_node_facts

- name: add hosts to site1  group
  add_host:
    name: "{{ item.tags.Name }}"
    username: "{{ item.tags.Student }}"
    short_name: "{{ item.tags.short_name }}"
    ansible_host: "{{ item.public_ip_address }}"
    ansible_user: "{{ item.tags.username }}"
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    groups: lab_hosts,managed_nodes, site1
  with_items:
    - "{{ node1_node_facts.instances }}"
    - "{{ node2_node_facts.instances }}"
  changed_when: false

- name: add hosts to site2  group
  add_host:
    name: "{{ item.tags.Name }}"
    username: "{{ item.tags.Student }}"
    short_name: "{{ item.tags.short_name }}"
    ansible_host: "{{ item.public_ip_address }}"
    ansible_user: "{{ item.tags.username }}"
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    groups: lab_hosts,managed_nodes, site2
  with_items:
    - "{{ node3_node_facts.instances }}"
    - "{{ node4_node_facts.instances }}"
  changed_when: false
