---
# old way
# - set_fact:
#     ansible_hub_node_ami:
#       image_id: "{{ pre_build_hub_ami[ec2_region] }}"

- name: Get private automation hub ami
  ec2_ami_info:
    region: "{{ ec2_region }}"
    owners: "962147768365"
    filters:
      name: "automation_hub*"
      architecture: "x86_64"
  register: amis

- name: Save private automation hub ami
  set_fact:
    ansible_hub_node_ami: >
      {{ amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}
