---
- name: find ami for rhel7 node
  ec2_ami_info:
    region: "{{ ec2_region }}"
    owners: "{{ ec2_info[rhel7].owners }}"
    filters:
      name: "{{ ec2_info[rhel7].filter }}"
      architecture: "{{ ec2_info[rhel7].architecture }}"
  register: rhel7amis

- name: save rhel7 ami details
  set_fact:
    node_ami_rhel7: >
      {{ rhel7amis.images | selectattr('name', 'defined') | sort(attribute='name') | last }}

- name: find ami for rhel8 node
  ec2_ami_info:
    region: "{{ ec2_region }}"
    owners: "{{ ec2_info[rhel8].owners }}"
    filters:
      name: "{{ ec2_info[rhel8].filter }}"
      architecture: "{{ ec2_info[rhel8].architecture }}"
  register: rhel7amis

- name: save rhel8 ami details
  set_fact:
    node_ami_rhel8: >
      {{ rhel8amis.images | selectattr('name', 'defined') | sort(attribute='name') | last }}
