---
- name: change password to workshop default
  ansible.netcommon.cli_command:
    command: "{{item}}"
    prompt:
      - "New password"
      - "Retype new password"
    answer:
      - "{{admin_password}}1"
      - "{{admin_password}}1"
    check_all: true
  loop:
    - "configure"
    - "rollback"
    - "set system root-authentication plain-text-password"
    - "commit"

- name: turn on netconf on port 830
  junipernetworks.junos.junos_netconf:
