---
- name: Install MySQL, PHP, Git
  yum:
    name:
      - mariadb-server
      - php
      - php-fpm
      - php-mysqlnd
      - php-pdo
      - python36
      - git
      - rsync
    state: present
  notify: restart nginx

- name: Enable TCP port 9000 for php-fpm
  lineinfile:
    path: /etc/php-fpm.d/www.conf
    regexp: '^listen ='
    line: 'listen = 127.0.0.1:9000'
  notify: restart php-fpm

- name: Start Services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - mariadb
    - php-fpm
  notify: restart nginx

- name: Set permissions on the PHP Session directory
  file:
    path: /var/lib/php/session/
    owner: nginx
    group: nginx
    mode: 0777
    state: directory

- name: Create users directory on server
  file:
    path: /usr/share/nginx/html/
    state: directory

- name: Copy users file to server
  template:
    src: templates/index.php.j2
    dest: /usr/share/nginx/html/index.php

- name: Copy list file to server
  template:
    src: templates/list.php.j2
    dest: /usr/share/nginx/html/list.php

- name: Install PyMySQL
  pip:
    name: PyMySQL

- name: Create a new database with name 'workshop'
  mysql_db:
    name: workshop
    state: present

- name: Copy SQL template to server
  template:
    src: templates/workshop.sql.j2
    dest: /tmp/workshop.sql
  register: workshopsql

- name: Import SQL file into workshop database
  mysql_db:
    state: import
    name: workshop
    target: /tmp/workshop.sql
  when: workshopsql.changed
