---
- name: GRAB ZONE ID
  route53_zone:
    zone: "{{workshop_dns_zone}}"
  register: AWSINFO

- name: GRAB ROUTE53 INFORMATION
  route53_info:
    type: A
    query: record_sets
    hosted_zone_id: "{{AWSINFO.zone_id}}"
    start_record_name: "login.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    max_items: 1
  register: record_sets

- name: DELETE DNS ENTRIES FOR ATTENDANCE HOST
  become: false
  route53:
    state: "{{ s3_state }}"
    zone: "{{workshop_dns_zone}}"
    record: "login.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    type: A
    value: "{{ (records | first | first)['Value'] }}"
  vars:
    records: '{{record_sets.ResourceRecordSets | selectattr("Name", "match", "login" + "." + ec2_name_prefix|lower + "." + workshop_dns_zone) | map(attribute="ResourceRecords") | list }}'
  when: records | length > 0
