---
tower_credentials:
  - name: AWX-Collection-tests-tower_workflow_job_template-scm-cred
    description: ''
    inputs: {}
    organization:
      name: Default
      type: organization
    credential_type:
      name: Source Control
      kind: scm
      type: credential_type
    natural_key:
      organization:
        name: Default
        type: organization
      name: AWX-Collection-tests-tower_workflow_job_template-scm-cred
      credential_type:
        name: Source Control
        kind: scm
        type: credential_type
      type: credential
  - name: Demo Credential
    description: ''
    organization: null
    inputs:
      username: admin
    credential_type:
      name: Machine
      kind: ssh
      type: credential_type
    user:
      username: admin
      type: user
    natural_key:
      organization: null
      name: Demo Credential
      credential_type:
        name: Machine
        kind: ssh
        type: credential_type
      type: credential
