---
tower_inventories:
  - name: 2nd Testing Inventory
    description: ''
    kind: ''
    host_filter: null
    organization:
      name: Satellite
      type: organization
    natural_key:
      organization:
        name: Satellite
        type: organization
      name: 2nd Testing Inventory
      type: inventory
  - name: Testing Inventory
    description: ''
    kind: ''
    host_filter: null
    organization:
      name: Satellite
      type: organization
    natural_key:
      organization:
        name: Satellite
        type: organization
      name: Testing Inventory
      type: inventory
