---
tower_organizations:
  - name: Satellite
    description: Satellite
    max_hosts: 0
    custom_virtualenv: null
    related:
      notification_templates_started: []
      notification_templates_success: []
      notification_templates_error:
        - name: irc-satqe-chat-notification
      notification_templates_approvals: []
  - name: Default
    description: Default
    max_hosts: 0
    custom_virtualenv: null
    related:
      notification_templates_started: []
      notification_templates_success: []
      notification_templates_error: []
      notification_templates_approvals: []
