---
# region where the nodes will live
ec2_region: us-east-1
# name prefix for all the VMs
ec2_name_prefix: TESTWORKSHOP
# amount of work benches to provision
student_total: 2
# workshop is put into isecurity mode
workshop_type: 'security'
security_console: 'qradar'
## Optional Variables
admin_password: ansible
windows_password: Ansible+Red*Hat19!20
create_login_page: false
towerinstall: true
dns_type: aws
