---
- name: Create tmp directory to store AAP tar.gz
  tempfile:
    state: directory
    suffix: "aapbundle"
  register: tempdir

- name: copy AAP tar.gz
  copy:
    src: "{{ aap_archive | default(playbook_dir + '/aap.tar.gz') }}"
    dest: "{{ tempdir.path }}/aap.tar.gz"

- name: Create directory for automation controller
  file:
    path: "{{ aap_dir }}"
    state: directory

- name: Extract AAP tar.gz install
  unarchive:
    src: "{{ tempdir.path }}/aap.tar.gz"
    dest: "{{ aap_dir }}"
    remote_src: true
    extra_opts: ['--strip-components=1', '--show-stored-names']

- name: Register and subscribe
  community.general.redhat_subscription:
    state: present
    username: "{{ redhat_username }}"
    password: "{{ redhat_password }}"
    auto_attach: true
