---
- name: Copy signing script to the PAH server
  copy:
    src: "signing_service.sh"
    dest: "{{ aap_dir }}"

- name: Create a gpg key description from template
  template:
    src: "gpg.txt.j2"
    dest: "{{ aap_dir }}/gpg.txt"

- name: Create a gpg key from description
  ansible.builtin.shell: "gpg --batch --gen-key gpg.txt"
  args:
    chdir: "{{ aap_dir }}"

- name: GPG export private key
  ansible.builtin.shell: "gpg --output {{ aap_dir }}/galaxy_signing_service.gpg --armor --export-secret-key"

- name: GPG export public key
  ansible.builtin.shell: "gpg --output /home/{{ username }}/galaxy_signing_service.asc --armor --export"

- name: Delete default gpg vault
  file:
    state: absent
    path: "/home/{{ username }}/.gnupg"
