- name: Configure Hub node
  include_tasks: "1_configurehub.yml"
  when: not teardown|bool

- name: setup DNS specific information
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ role_path }}/tasks/40_dns/{{ dns_type }}.yml"
    - "{{ role_path }}/tasks/40_dns/none.yml"
  when: pre_build or automation_hub | bool

- name: setup ssl cert
  include_tasks: "50_ssl.yml"
  when: automation_hub | bool and not teardown|bool
