---
- name: redhat subscription
  include_tasks: "5_redhat_sub.yml"
  when: pemexist

- name: aap setup
  include_tasks: "10_aap_setup.yml"
  tags:
    - aap_setup
  when: not teardown

- name: AAP Signing bits included?
  set_fact:
    aap_signing_bits_included: "{{ __aap_version is version('2.2.0', '>=')  }}"
  when: not teardown

- name: Setup signing
  include_tasks: "20_setup_signing.yml"
  when: not teardown and enable_signing and aap_signing_bits_included

- name: install hub
  include_tasks: "30_hub.yml"
  when: not teardown

- name: setup DNS specific information
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ role_path }}/tasks/40_dns/{{ dns_type }}.yml"
    - "{{ role_path }}/tasks/40_dns/none.yml"

- name: setup ssl cert
  include_tasks: "50_ssl.yml"
  when: not teardown
