---
- name: aap setup
  include_tasks: "10_aap_setup.yml"
  tags:
    - aap_setup
  when: not teardown

- name: install hub
  include_tasks: "30_hub.yml"
  when: not teardown

- name: setup DNS specific information
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ role_path }}/tasks/40_dns/{{ dns_type }}.yml"
    - "{{ role_path }}/tasks/40_dns/none.yml"

- name: setup ssl cert
  include_tasks: "50_ssl.yml"
  when: not teardown
