---
- name: Verify presence of automation-controller.nginx.conf
  ansible.builtin.stat:
    path: /etc/nginx/conf.d/automation-controller.nginx.conf
  register: automation_controller_nginx_conf_file

- name: Copy /etc/nginx/nginx.conf file on controller to conf.d/automation-controller.nginx.conf
  ansible.builtin.copy:
    src: /etc/nginx/nginx.conf
    dest: /etc/nginx/conf.d/automation-controller.nginx.conf
    remote_src: yes
  when: not automation_controller_nginx_conf_file.stat.exists

- name: Replace add_header X-Frame-Options DENY with CSP frame-ancestors self in automation-controller.nginx.conf
  ansible.builtin.lineinfile:
    path: /etc/nginx/conf.d/automation-controller.nginx.conf
    regexp: '^(.*)add_header X-Frame-Options \"DENY\"\;'
    line: >-
      \1add_header Content-Security-Policy "frame-ancestors 'self';";
    backrefs: yes
    owner: root
    group: root
    mode: '0644'
  register: add_header_csp
  retries: 10
  until: add_header_csp is not changed

- name: Apply our systemd service file (instead of RPM file)
  ansible.builtin.template:
    src: code-server.service.j2
    dest: /etc/systemd/system/code-server.service
    owner: "{{ username }}"
    group: wheel
    mode: '0744'

- name: daemon-reload, enable and start code-server
  ansible.builtin.systemd:
    name: code-server
    enabled: true
    state: restarted
    daemon_reload: true
