#REMOVE HARD CODED SSH_KEY VAR
    - name: REMOVE HARD CODED SSH KEY VAR IN INVENTORY
      uri:
        url: "https://{{ansible_host}}/api/v2/inventories/2/"
        user: "admin"
        password: "{{admin_password}}"
        method: PATCH
        validate_certs: False
        force_basic_auth: yes
        body_format: json
        body: ' {"variables": ""}'
        status_code:
          - 200
          - 204
      register: result_uri
      ignore_errors: yes

#JOB TEMPLATES
#Commenting out as students will not create this#
    # - name: CREATE BACKUP JOB IN TOWER
    #   tower_job_template:
    #     name: "Network-Backup"
    #     job_type: "run"
    #     inventory: "Workshop Inventory"
    #     project: "Workshop Project"
    #     playbook: "network_backup.yml"
    #     credential: "Workshop Credential"
    #     state: "present"
    #     limit: "cisco"
    #     tower_username: admin
    #     tower_password: "{{ admin_password }}"
    #     tower_host: "{{ ansible_host }}"
    #     tower_verify_ssl: no

    - name: CREATE SHOW COMMAND JOB IN TOWER
      tower_job_template:
        name: "Network-Commands"
        job_type: "run"
        inventory: "Workshop Inventory"
        project: "Workshop Project"
        playbook: "network_commands.yml"
        credential: "Workshop Credential"
        state: "present"
        limit: "cisco"
        survey_enabled: yes
        survey_spec: "{{ lookup('template', './templates/survey_spec.json') }}"
        tower_username: admin
        tower_password: "{{ admin_password }}"
        tower_host: "{{ ansible_host }}"
        tower_verify_ssl: no

    - name: CREATE USER JOB IN TOWER
      tower_job_template:
        name: "Network-User"
        job_type: "run"
        inventory: "Workshop Inventory"
        project: "Workshop Project"
        playbook: "network_user.yml"
        credential: "Workshop Credential"
        state: "present"
        limit: "cisco"
        tower_username: admin
        tower_password: "{{ admin_password }}"
        tower_host: "{{ ansible_host }}"
        tower_verify_ssl: no

    - name: CREATE SYSTEM JOB IN TOWER
      tower_job_template:
        name: "Network-System"
        job_type: "run"
        inventory: "Workshop Inventory"
        project: "Workshop Project"
        playbook: "network_system.yml"
        credential: "Workshop Credential"
        state: "present"
        limit: "cisco"
        tower_username: admin
        tower_password: "{{ admin_password }}"
        tower_host: "{{ ansible_host }}"
        tower_verify_ssl: no

    - name: CREATE TIME JOB IN TOWER
      tower_job_template:
        name: "Network-Time"
        job_type: "run"
        inventory: "Workshop Inventory"
        project: "Workshop Project"
        playbook: "network_time.yml"
        credential: "Workshop Credential"
        state: "present"
        limit: "cisco"
        tower_username: admin
        tower_password: "{{ admin_password }}"
        tower_host: "{{ ansible_host }}"
        tower_verify_ssl: no

    - name: CREATE RESTORE JOB IN TOWER
      tower_job_template:
        name: "Network-Restore"
        job_type: "run"
        inventory: "Workshop Inventory"
        project: "Workshop Project"
        playbook: "network_restore.yml"
        credential: "Workshop Credential"
        state: "present"
        limit: "cisco"
        tower_username: admin
        tower_password: "{{ admin_password }}"
        tower_host: "{{ ansible_host }}"
        tower_verify_ssl: no

#JOB TEMPLATE PERMISSIONS
    - name: ENSURE THAT NWOP CAN EXECUTE BACKUP AND SHOW COMMANDS
      tower_role:
        user: network-operator
        role: execute
        job_template: "{{ item }}"
        state: present
        tower_username: admin
        tower_password: "{{ admin_password }}"
        tower_host: "{{ ansible_host }}"
        validate_certs: no
      loop:
        - "Network-Commands"
#Commenting out backup as students will now specify this#
#        - "Network-Backup"

    - name: ENSURE THAT NW ORG CAN USE THE WS INV
      tower_role:
        role: use
        inventory: "Workshop Inventory"
        team: "{{ item }}"
        state: present
        tower_username: admin
        tower_password: "{{ admin_password }}"
        tower_host: "{{ ansible_host }}"
        validate_certs: no
      tags:
        - inv
      loop:
        - Netops
        - Netadmin
