    - name: ADD CREDENTIAL INTO TOWER
      tower_credential:
        username: ec2-user
        name: "Workshop Credential"
        ssh_key_data: "{{ lookup('file', playbook_dir +'/' + ec2_name_prefix + '/' + ec2_name_prefix + '-private.pem') }}"
        kind: ssh
        organization: REDHAT NETWORK ORGANIZATION
        tower_username: admin
        tower_password: "{{ admin_password }}"
        tower_host: "{{ ansible_host }}"
        tower_verify_ssl: no

    - name: IMPORT INVENTORY
      shell: 'tower-manage inventory_import --source=/home/{{ username }}/networking-workshop/lab_inventory/hosts --inventory-name="Workshop Inventory"'
