---
- name: add tower project for rhel_90 workshop
  awx.awx.tower_project:
    name: "Workshop Project"
    organization: "Default"
    scm_type: git
    scm_url: "https://github.com/ansible/workshop-examples"
    tower_username: admin
    tower_password: "{{ admin_password }}"
    tower_host: "https://{{ ansible_host }}"
    tower_verify_ssl: false

- name: install demo
  vars:
    my_tower_username: admin
    my_tower_password: "{{ admin_password }}"
    my_tower_host: "https://{{ ansible_host }}"
    demo: hardening
  include_role:
    name: "ansible.product_demos.install_demo"

- name: install demo
  vars:
    my_tower_username: admin
    my_tower_password: "{{ admin_password }}"
    my_tower_host: "https://{{ ansible_host }}"
    demo: turn_off_community_grid
  include_role:
    name: "ansible.product_demos.install_demo"
