- name: DNS FOR STUDENT WEBPAGE FOR US-EAST-1
  become: False
  route53:
    state: "{{ s3_state }}"
    zone: "{{workshop_dns_zone}}"
    record: "{{username}}.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    type: A
    overwrite: yes
    value: "{{ansible_host}}"
  delegate_to: localhost

- name: CERTBOT FOR TOWER
  include_tasks: "tower.yml"
  when: towerinstall
