admin_password: ansible
workshop_dns_zone: "rhdemo.io"
s3_state: "present"
teardown: false
towerinstall: false
website_information: ""
dns_information: "No errors with DNS"
workshop_type: ""
valid_workshop_types:
  - networking
  - f5
  - rhel
  - security
  - storage
  - windows
network_type: multivendor
valid_network_types:
  - cisco
  - arista
  - juniper
  - multivendor
security_console: qradar
valid_security_console_types:
  - splunk
  - qradar
