- fail:
    msg: "Amazon AWS does not allow underscores _ for s3 websites, please see https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html"
  when: '"_" in ec2_name_prefix'

- name: create student webpage
  template:
    src: ./templates/index.html.j2
    dest: "./{{ ec2_name_prefix|lower }}-index.html"
  when: s3_state == 'present'

- name: create s3 bucket
  s3_bucket:
    name: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone|lower}}"
    state: "{{ s3_state }}"
    region: "{{ec2_region}}"
    force: yes
  tags:
     - s3website

- name: enable web hosting
  s3_website:
   name: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone|lower}}"
   state: "{{ s3_state }}"
   region: "{{ec2_region}}"
   suffix: "{{ ec2_name_prefix|lower }}-index.html"
  register: s3_site
  when: s3_state == 'present'
  tags:
     - s3website

- name: DNS for student webpage
  route53:
    state: "{{ s3_state }}"
    zone: "{{workshop_dns_zone}}"
    record: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    type: CNAME
    overwrite: yes
    value: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}.s3-website-{{ec2_region}}.amazonaws.com"
  when:
    - s3_state == 'present'
    - ec2_region == 'us-east-1'
  tags:
     - s3website

- name: DNS for student webpage
  route53:
    state: "{{ s3_state }}"
    zone: "{{workshop_dns_zone}}"
    record: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    type: CNAME
    overwrite: yes
    value: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}.s3-website.{{ec2_region}}.amazonaws.com"
  when:
    - s3_state == 'present'
    - ec2_region != 'us-east-1'
  tags:
     - s3website

- name: PUT student webpage
  s3_sync:
    bucket: "{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    region: "{{ec2_region}}"
    file_root: ./
    mime_map:
      .html: text/html
    permission: public-read
    include: "{{ ec2_name_prefix|lower }}-index.html"
  when: s3_state == 'present'
  tags:
     - s3website
