---
- name: website creation and deletion block
  block:
    - name: CREATE STUDENT WEBPAGE
      template:
        src: ./templates/index.html.j2
        dest: "{{ playbook_dir }}/{{ ec2_name_prefix }}/{{ ec2_name_prefix|lower }}-index.html"
      when: s3_state == 'present'

    - name: CREATE S3 BUCKET
      s3_bucket:
        name: "{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone|lower }}"
        state: "{{ s3_state }}"
        region: "{{ ec2_region }}"
        force: true
      retries: 4
      delay: 15
      register: s3_result
      until:
        - s3_result.failed == false

    - name: ENABLE WEB HOSTING
      s3_website:
        name: "{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone|lower }}"
        state: "{{ s3_state }}"
        region: "{{ ec2_region }}"
        suffix: "{{ ec2_name_prefix|lower }}-index.html"
      register: s3_site
      when: s3_state == 'present'

    - name: DNS FOR STUDENT WEBPAGE FOR US-EAST-1
      route53:
        state: "{{ s3_state }}"
        zone: "{{ workshop_dns_zone }}"
        record: "{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone }}"
        type: CNAME
        overwrite: true
        value: "{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone }}.s3-website-{{ ec2_region }}.amazonaws.com"
      when:
        - ec2_region == 'us-east-1'

    - name: DNS FOR WEBPAGE
      route53:
        state: "{{ s3_state }}"
        zone: "{{ workshop_dns_zone }}"
        record: "{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone }}"
        type: CNAME
        overwrite: true
        value: "{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone }}.s3-website.{{ ec2_region }}.amazonaws.com"
      when:
        - ec2_region != 'us-east-1'

    - name: PUT STUDENT WEBPAGE
      s3_sync:
        bucket: "{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone }}"
        region: "{{ ec2_region }}"
        file_root: "{{ playbook_dir }}/{{ ec2_name_prefix }}"
        mime_map:
          .html: text/html
        permission: public-read
        include: "{{ ec2_name_prefix|lower }}-index.html"
      when: s3_state == 'present'

    - name: SET WEBSITE INFORMATION VARIABLE
      set_fact:
        website_information: "Website created at http://{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone|lower }}"
  rescue:
    - debug:
        msg: 'issue with S3 website'

    - name: provide error information
      set_fact:
        dns_information: "aws_workshop_login_page role hit an issue"
