# Tower LDAP Integration
dns_domain_name: "ansibleworkshop.com"
domain_admin_password: "MyP@ssw0rd21"

ldap_basedn: "DC=ansibleworkshop,DC=com"
ldap_search_base: "{{ ldap_basedn }}"
ldap_access_filter: "(&(objectClass=user)(memberOf=CN=Ansible Users,CN=Users,{{ ldap_search_base }}))"
tower_ldap_search_dn: "CN=Users,{{ ldap_search_base }}"
