---
- name: Print out connection vars to hosts
  ansible.builtin.debug:
    msg:
      - "ansible_host {{ ansible_host }}"
      - "ansible_user {{ ansible_user }}"
      - "ansible_ssh_private_key_file {{ ansible_ssh_private_key_file }}"
      - "groups {{ groups }}"

- name: Wait 400 seconds (using wait_for_connection)
  ansible.builtin.wait_for_connection:
    delay: 0
    timeout: 400

# This wait_for_connection task can't be part of manage_ec2_instances
# because you can't use groups with delegate_to, see:
# https://github.com/ansible/ansible/issues/35195
# also the meta refresh_inventory won't help, as its intended for dynamic inventory
