---
- name: ensure workshop folder {{ ec2_name_prefix }} exists
  file:
    path: "{{ output_dir }}"
    state: directory

- name: Download manifest.zip
  when:
    - manifest_download_url is defined
  block:
    - name: Enforce use of user/password for manifest download
      ansible.builtin.assert:
        that:
          - manifest_download_url.startswith('https://')
          - manifest_download_user is defined
          - manifest_download_password is defined
        fail_msg: >-
          manifest_download_url must be secure and requires manifest_download_user
          and manifest_download_password.

    - name: Download manifest.zip
        ansible.builtin.get_url:
          url: "{{ manifest_download_url }}"
          dest: "{{ playbook_dir }}/manifest.zip"
          username: "{{ manifest_download_user }}"
          password: "{{ manifest_download_password }}"
          force_basic_auth: true

- name: check license block
  block:
    - name: Check that the manifest.zip exists
      stat:
        path: "{{ playbook_dir }}/manifest.zip"
      register: manifest_result
    - fail:
        msg: "Need a manifest file at {{ playbook_dir }}/manifest.zip"
      when:
        - not manifest_result.stat.exists
  rescue:
    - name: checking for base64_manifest since no manifest.zip found
      debug:
        msg: checking for variable base64_manifest
    - name: fail if there is also no base64_manifest
      fail:
        msg: no manifest.zip file found and no base64_manifest variable found
      when: base64_manifest is not defined
    - name: Rescue worked, base64 var found
      debug:
        msg: The variable base64_manifest was located
