---
argument_specs:
  main:
    short_description: Install Splunk Enterprise.
    options:
      username:
        description: The workshop username.
        type: str
        required: true
      ec2_name_prefix:
        description: A prefix for EC2 and DNS resources.
        type: str
        required: true
      workshop_dns_zone:
        description: The base DNS zone for the workshop.
        type: str
        required: true
      student_total:
        description: The total number of students for the workshop.
        type: int
        required: true
      teardown:
        description: Whether to execute teardown or creation.
        type: bool
        required: true
