---
- block:
  - name: Download Microsoft Visual C++ Redistributable Packages needed for SmartConsole
    win_chocolatey:
      name:
        - vcredist2010
        - vcredist2012
      state: present

  - name: Ensure the required NuGet package provider version is installed
    win_shell: Find-PackageProvider -Name Nuget -ForceBootstrap -IncludeDependencies -Force

  - name: Install Pscx needed for unzip step later
    win_psmodule:
      name: pscx
      allow_clobber: true

  - name: Check if SmartConsole is downloaded
    win_stat:
      path: C:\Temp\SmartConsole.exe
    register: smartconsole

  - name: Download SmartConsole to specified path only if modified
    win_get_url:
      url: https://s3.amazonaws.com/linklight.securityautomation/Check_Point_SmartConsole_R80_20_jumbo_HF_B055_Win.exe
      dest: C:\Temp\SmartConsole.exe
      checksum: 424bd9ccac118c5a9c9e006b89f21d0a8b4f944b
      force: yes
    when: not smartconsole.stat.exists
    register: win_get_smartconsole
    until: win_get_smartconsole is success
    retries: 5

  - name: Unpack SmartConsole archive
    win_unzip:
      src: C:\Temp\SmartConsole.exe
      dest: C:\Temp\SmartConsole
      creates: C:\Temp\SmartConsole\SmartConsole.exe

  - name: Copy installer answer file to appropriate place
    win_copy:
      src: setup.iss
      dest: C:\Temp\SmartConsole\setup.iss

  - name: Execute SmartConsole installer
    win_command: C:\Temp\SmartConsole\SmartConsole.exe -s setup.iss

