---

# These are the default variables common to most tower_configuration and _utilities roles
# You shouldn't need to define them again and again but they should be defined
#tower_hostname: "{{ inventory_hostname }}"
#tower_username: "admin"
#tower_password: ""
#tower_oauthtoken: ""
#tower_config_file: ""
#tower_validate_certs: false

# These are the default variables specific to the tower_settings role

# list of dicts (or a single dict) describing the Tower settings
tower_settings: []
# possible fields:
#- settings:  # either this field or name/value is mandatory
#    SETTING_NAME: setting_value
#- name: "SETTING_NAME"
#  value: SETTING_VALUE

tower_configuration_settings_secure_logging: "{{tower_configuration_secure_logging | default(false)}}"
