---

# Create Job Template
- name: Add Tower Job Templates
  awx.awx.tower_job_template:
    name:                           "{{ tower_templates_item.name }}"
    new_name:                       "{{ tower_templates_item.new_name | default(omit) }}"
    description:                    "{{ tower_templates_item.description | default('') }}"
    job_type:                       "{{ tower_templates_item.job_type | default('run') }}"
    inventory:                      "{{ tower_templates_item.inventory.name | default( tower_templates_item.inventory | default('')) }}"
    organization:                   "{{ tower_templates_item.organization.name | default( tower_templates_item.organization | default('')) }}"
    project:                        "{{ tower_templates_item.project.name | default( tower_templates_item.project | default('')) }}"
    playbook:                       "{{ tower_templates_item.playbook }}"
    credentials:                    "{{ tower_templates_item.credentials | default(tower_templates_item.related.credentials | default([]) | map(attribute='name') | list ) }}"
    forks:                          "{{ tower_templates_item.forks | default(0) }}"
    limit:                          "{{ tower_templates_item.limit | default(omit) }}"
    verbosity:                      "{{ tower_templates_item.verbosity | default(omit) }}"
    extra_vars:                     "{{ tower_templates_item.extra_vars | default(omit) }}"
    job_tags:                       "{{ tower_templates_item.job_tags | default('') }}"
    force_handlers:                 "{{ tower_templates_item.force_handlers | default(omit) }}"
    skip_tags:                      "{{ tower_templates_item.skip_tags | default(omit) }}"
    start_at_task:                  "{{ tower_templates_item.start_at_task | default(omit) }}"
    diff_mode:                      "{{ tower_templates_item.diff_mode | default('false') }}"
    use_fact_cache:                 "{{ tower_templates_item.use_fact_cache | default('false') }}"
    host_config_key:                "{{ tower_templates_item.host_config_key | default(omit) }}"
    ask_scm_branch_on_launch:       "{{ tower_templates_item.ask_scm_branch_on_launch | default(omit) }}"
    ask_diff_mode_on_launch:        "{{ tower_templates_item.ask_diff_mode_on_launch | default('false') }}"
    ask_variables_on_launch:        "{{ tower_templates_item.ask_variables_on_launch | default('false') }}"
    ask_limit_on_launch:            "{{ tower_templates_item.ask_limit_on_launch | default('false') }}"
    ask_tags_on_launch:             "{{ tower_templates_item.ask_tags | default( tower_templates_item.ask_tags_on_launch | default('false')) }}"
    ask_skip_tags_on_launch:        "{{ tower_templates_item.ask_skip_tags | default( tower_templates_item.ask_skip_tags_on_launch | default('false')) }}"
    ask_job_type_on_launch:         "{{ tower_templates_item.ask_job_type_on_launch | default(omit) }}"
    ask_verbosity_on_launch:        "{{ tower_templates_item.ask_verbosity_on_launch | default('false') }}"
    ask_inventory_on_launch:        "{{ tower_templates_item.ask_inventory_on_launch | default(omit) }}"
    ask_credential_on_launch:       "{{ tower_templates_item.ask_credential_on_launch | default(omit) }}"
    survey_enabled:                 "{{ tower_templates_item.survey_enabled | default('false') }}"
    survey_spec:                    "{{ tower_templates_item.related.survey_spec | default(tower_templates_item.survey | default(omit)) }}"
    become_enabled:                 "{{ tower_templates_item.become_enabled | default(omit) }}"
    allow_simultaneous:             "{{ tower_templates_item.allow_simultaneous | default('false') }}"
    timeout:                        "{{ tower_templates_item.timeout | default(omit) }}"
    custom_virtualenv:              "{{ tower_templates_item.custom_virtualenv | default(omit) }}"
    job_slice_count:                "{{ tower_templates_item.job_slice_count | default(1) }}"
    webhook_service:                "{{ tower_templates_item.webhook_service | default(omit) }}"
    webhook_credential:             "{{ tower_templates_item.webhook_credential | default(omit) }}"
    scm_branch:                     "{{ tower_templates_item.scm_branch | default(omit) }}"
    labels:                         "{{ tower_templates_item.labels | default(tower_templates_item.related.labels | default([]) | map(attribute='name') | list ) }}"
    state:                          "{{ tower_templates_item.state | default(tower_state | default('present')) }}"
    notification_templates_started: "{{ tower_templates_item.notification_templates_started | default(tower_templates_item.related.notification_templates_started | default([]) | map(attribute='name') | list ) }}"
    notification_templates_success: "{{ tower_templates_item.notification_templates_success | default(tower_templates_item.related.notification_templates_success | default([]) | map(attribute='name') | list ) }}"
    notification_templates_error:   "{{ tower_templates_item.notification_templates_error | default(tower_templates_item.related.notification_templates_error | default([]) | map(attribute='name') | list ) }}"
    tower_username:                 "{{ tower_username | default(omit) }}"
    tower_password:                 "{{ tower_password | default(omit) }}"
    tower_oauthtoken:               "{{ tower_oauthtoken | default(omit) }}"
    tower_host:                     "{{ tower_hostname }}"
    tower_config_file:              "{{ tower_config_file | default(omit) }}"
    validate_certs:                 "{{ tower_validate_certs | default('true') }}"
  loop: "{{ tower_templates }}"
  loop_control:
    loop_var: tower_templates_item
  no_log: "{{ tower_configuration_job_templates_secure_logging }}"
