---

- name: Add Credentials
  awx.awx.tower_credential:
    name:                           "{{ tower_credentials_item.name }}"
    new_name:                       "{{ tower_credentials_item.new_name | default(omit) }}"
    description:                    "{{ tower_credentials_item.description | default(omit) }}"
    organization:                   "{{ tower_credentials_item.organization.name | default( tower_credentials_item.organization | default(omit)) }}"
    credential_type:                "{{ tower_credentials_item.credential_type.name | default( tower_credentials_item.credential_type | default(omit)) }}"
    kind:                           "{{ tower_credentials_item.credential_type.kind | default( tower_credentials_item.kind | default(omit)) }}"
    inputs:                         "{{ tower_credentials_item.inputs | default(omit) }}"
    user:                           "{{ tower_credentials_item.user.username | default( tower_credentials_item.user | default(omit)) }}"
    team:                           "{{ tower_credentials_item.team.name | default( tower_credentials_item.team | default(omit)) }}"
    update_secrets:                 "{{ tower_credentials_item.update_secrets | default('true') }}"
    state:                          "{{ tower_credentials_item.state | default(tower_state | default('present')) }}"
    tower_username:                 "{{ tower_username | default(omit) }}"
    tower_password:                 "{{ tower_password | default(omit) }}"
    tower_oauthtoken:               "{{ tower_oauthtoken | default(omit) }}"
    tower_host:                     "{{ tower_hostname }}"
    tower_config_file:              "{{ tower_config_file | default(omit) }}"
    validate_certs:                 "{{ tower_validate_certs | default(omit) }}"
  loop: "{{ tower_credentials }}"
  loop_control:
    loop_var: tower_credentials_item
  no_log: "{{ tower_configuration_credentials_secure_logging }}"
