---
- name: F5 instance size list length
  ansible.builtin.debug:
    msg: "RHEL instance size list length: {{ ec2_info[f5node].size | length }}"

- name: Initialize/reset list count
  ansible.builtin.set_fact:
    list_count: "reset"

- name: Call F5 retry tasks include
  ansible.builtin.include_tasks: f5/f5_loop.yml

- name: RHEL instance size list length
  ansible.builtin.debug:
    msg: "RHEL instance size list length: {{ ec2_info[rhel].size | length }}"

- name: Initialize/reset list count
  ansible.builtin.set_fact:
    list_count: "reset"

- name: Call RHEL retry tasks include
  ansible.builtin.include_tasks: f5/rhel_loop.yml

############## eni check ##############

- name: grab all network interfaces for VPC 1 (workshop_type f5)
  amazon.aws.ec2_eni_info:
    region: "{{ ec2_region }}"
    filters:
      vpc-id: "{{ ec2_vpc_id }}"
  register: eni_facts_1

- name: Disable Source/Dest check on instance {{ ec2_vpc_id }} (workshop_type f5)
  amazon.aws.ec2_eni:
    eni_id: "{{ item['network_interface_id'] }}"
    region: "{{ ec2_region }}"
    source_dest_check: false
  with_items:
    - "{{ eni_facts_1['network_interfaces'] }}"
...
