---
- set_fact:
    async_timeout_seconds: "{{ student_total * 60 }}"
    async_wait_for_retries: "{{ student_total * 10 }}"

- name: Create EC2 Block - SECURITY MODE
  block:
    - name: Import Create EC2 Tasks
      import_tasks: security_includes/security_ec2_create_instances.yml
  rescue:
    - name: RESCUE RETRY - Import Create EC2 Tasks
      import_tasks: security_includes/security_ec2_create_instances.yml


- name: EC2 Tags Block - SECURITY MODE
  block:
    - name: Import EC2 Tags Tasks
      import_tasks: security_includes/security_ec2_tags.yml
  rescue:
    - name: RESCUE RETRY - Import EC2 Tags Tasks
      import_tasks: security_includes/security_ec2_tags.yml

- name: Create EC2 Subnet2 ENI - SECURITY MODE
  block:
    - name: Import EC2 Subnet2 ENI
      import_tasks: security_includes/security_ec2_subnet2_eni.yml
  rescue:
    - name: RESCUE RETRY - Import EC2 Subnet2 ENI
      import_tasks: security_includes/security_ec2_subnet2_eni.yml


###############################################################################
# The CheckPoint GW
#
# This AWS Appliance Image requires all Elastic Network Interfaces (ENIs) to be
# present at instance creation time because there does not appear to be
# a post-instantiation way to add it because the CPGW does not feature
# a standard GNU userspace but instead an embedded linux style setup with
# limited availability to modify the instance after creation (in testing we
# found that even rebooting the instance with new ENIs attached did not cause
# them to be added.
- name: Create EC2 Check Point GW with ENI bookkeeping- SECURITY MODE
  block:
    - name: Import Check Point GW ENI Bookkeeping
      import_tasks: security_includes/security_ec2_checkpoint_gw_eni_bookkeeping.yml
  rescue:
    - name: RESCUE RETRY - Import Check Point GW ENI Bookkeeping
      import_tasks: security_includes/security_ec2_checkpoint_gw_eni_bookkeeping.yml
