---
- name: Create EC2 instances for private automation hub
  amazon.aws.ec2_instance:
    key_name: "{{ ec2_name_prefix }}-key"
    security_group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_info[control_type].size }}"
    image_id: "{{ ansible_control_node_ami.image_id }}"
    region: "{{ ec2_region }}"
    exact_count: 1
    network:
      assign_public_ip: true
    filters:
      "tag:Workshop_automation-hub": "{{ ec2_name_prefix }}-automation-hub"
    tags:
      Name: "{{ ec2_name_prefix }}-hub"
      Workshop_automation-hub: "{{ ec2_name_prefix }}-automation-hub"
      App: AnsibleWorkshop
      Workshop: "{{ ec2_name_prefix }}"
      Workshop_type: "{{ workshop_type }}"
      AWS_USERNAME: "{{ aws_user }}"
      Info: "AWS_USERNAME that provisioned this-> {{ aws_user }}"
      Ansible_Workshops: "This was provisioned through the ansible workshops provisioner"
      Students: "{{ student_total }}"
      username: "{{ ec2_info[control_type].username }}"
      short_name: "automation-hub"
      long_name: "automation-hub.{{ ec2_name_prefix }}.{{ workshop_dns_zone | default ('') }}"
      ansible-workshops: "true"
      owner: "{{ aws_user }}"
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_type: gp2
          volume_size: "{{ ec2_info[control_type].disk_space }}"
          delete_on_termination: true
  register: hub_output
