---
- name: s3 bucket for persistent storage of ec2 key exists
  amazon.aws.s3_bucket:
    name: "{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone|lower }}.private"
    state: present
    region: "{{ ec2_region }}"
    tags:
      ansible-workshops: "true"
  retries: 4
  delay: 15
  register: s3_result
  until: s3_result.failed == false

- name: Store SSH Key Pair
  amazon.aws.aws_s3:
    bucket: "{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone }}.private"
    mode: put
    object: "{{ec2_name_prefix}}-private.pem"
    src: "{{ playbook_dir }}/{{ ec2_name_prefix|lower }}/{{ ec2_name_prefix|lower }}-private.pem"
    encrypt: true
    region: "{{ ec2_region }}"
    permission: []
  when: create_key.changed

- name: Save Private key from S3 Bucket when not generating it
  amazon.aws.aws_s3:
    bucket: "{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone }}.private"
    mode: get
    object: "{{ ec2_name_prefix }}-private.pem"
    dest: "{{ playbook_dir }}/{{ ec2_name_prefix|lower }}/{{ ec2_name_prefix|lower }}-private.pem"
    encrypt: true
    region: "{{ ec2_region }}"
  when: not create_key.changed
