---
- name: make sure .ssh is created
  ansible.builtin.file:
    path: "/home/{{ username }}/.ssh/"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory

- name: Apply patch for runner fix PR759
  ansible.builtin.lineinfile:
    path: /usr/lib/python3.8/site-packages/ansible_runner/config/_base.py
    regexp: ".*--userns=keep-id.*"
    state: absent

##
# @todo @craig-br This needs immprovement. Multiple ssh-agent instances
# are running for each bash session
##
- name: add custom bashrc for student
  ansible.builtin.template:
    src: bashrc.j2
    dest: /home/{{ username }}/.bashrc
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

# Login into Red Hat registry
- name: Login to redhat registry
  containers.podman.podman_login:
    username: '{{ redhat_username }}'
    password: '{{ redhat_password }}'
    registry: '{{ ee_registry_name }}'
  become_user: "{{ username }}"
  register: login_registry
  until: login_registry is not failed
  retries: 5

- name: Copy over ssh config file for student
  ansible.builtin.template:
    src: sshconfig.j2
    dest: /home/{{ username }}/.ssh/config
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0700
