---
- name: aap setup for control node
  include_tasks: 10_aap_setup.yml
  tags:
    - aap_setup

- name: check to see if automation controller is already up and running
  uri:
    url: https://localhost/api/v2/ping/
    method: GET
    user: admin
    password: "{{ admin_password }}"
    validate_certs: false
    force_basic_auth: true
  register: check_controller
  ignore_errors: true
  failed_when: false
  when:
    - controllerinstall is defined
    - controllerinstall|bool

- name: install controller if knob is set
  include_tasks: "12_controller.yml"
  when:
    - controllerinstall is defined
    - controllerinstall|bool
    - check_controller.status != 200

- name: Install packages
  include_tasks: 15_package_dependencies.yml

- name: common workshop setup for control node
  include_tasks: 20_all_workshop.yml
