---
- name: Add ansible tower notifications
  awx.awx.tower_notification_template:
    name:                           "{{ tower_notifications_item.name }}"
    new_name:                       "{{ tower_notifications_item.new_name | default(omit) }}"
    description:                    "{{ tower_notifications_item.description | default(omit) }}"
    organization:                   "{{ tower_notifications_item.organization.name | default( tower_notifications_item.organization ) }}"
    notification_type:              "{{ tower_notifications_item.notification_type }}"
    notification_configuration:     "{{ tower_notifications_item.notification_configuration }}"
    messages:                       "{{ tower_notifications_item.messages | default(omit) | regex_replace('[ ]{2,}','') }}"
    # Depreciated Options
    username:                       "{{ tower_notifications_item.username | default(omit) }}"
    sender:                         "{{ tower_notifications_item.sender| default(omit) }}"
    recipients:                     "{{ tower_notifications_item.recipients | default(omit) }}"
    use_tls:                        "{{ tower_notifications_item.use_tls | default(omit)   }}"
    host:                           "{{ tower_notifications_item.host | default(omit) }}"
    use_ssl:                        "{{ tower_notifications_item.use_ssl | default(omit) }}"
    password:                       "{{ tower_notifications_item.password | default(omit) }}"
    port:                           "{{ tower_notifications_item.port | default(omit) }}"
    channels:                       "{{ tower_notifications_item.channels | default(omit) }}"
    token:                          "{{ tower_notifications_item.token | default(omit) }}"
    account_token:                  "{{ tower_notifications_item.account_token | default(omit) }}"
    from_number:                    "{{ tower_notifications_item.from_number | default(omit) }}"
    to_numbers:                     "{{ tower_notifications_item.to_numbers | default(omit) }}"
    account_sid:                    "{{ tower_notifications_item.account_sid | default(omit) }}"
    subdomain:                      "{{ tower_notifications_item.subdomain | default(omit) }}"
    service_key:                    "{{ tower_notifications_item.service_key | default(omit) }}"
    client_name:                    "{{ tower_notifications_item.client_name | default(omit) }}"
    message_from:                   "{{ tower_notifications_item.message_from | default(omit) }}"
    color:                          "{{ tower_notifications_item.color | default(omit) }}"
    notify:                         "{{ tower_notifications_item.notify | default(omit) }}"
    url:                            "{{ tower_notifications_item.url | default(omit) }}"
    headers:                        "{{ tower_notifications_item.headers | default(omit) }}"
    server:                         "{{ tower_notifications_item.server| default(omit) }}"
    nickname:                       "{{ tower_notifications_item.nickname | default(omit) }}"
    targets:                        "{{ tower_notifications_item.targets | default(omit) }}"
    # Tower Default Options
    state:                          "{{ tower_notifications_item.state | default(tower_state | default('present')) }}"
    tower_host:                     "{{ tower_hostname }}"
    tower_username:                 "{{ tower_username | default(omit) }}"
    tower_password:                 "{{ tower_password | default(omit) }}"
    tower_oauthtoken:               "{{ tower_oauthtoken | default(omit) }}"
    tower_config_file:              "{{ tower_config_file | default(omit) }}"
    validate_certs:                 "{{ validate_certs | default(tower_verify_ssl | default('false')) }}"
  loop: "{{ tower_notifications }}"
  loop_control:
    loop_var: tower_notifications_item
  no_log: "{{ tower_configuration_notifications_secure_logging }}"
