---
- name: MANAGE SPLUNK EC2 INSTANCES (SECURITY MODE)
  when: security_console == 'splunk'
  block:
    - name: grab facts for splunknode (SECURITY MODE)
      ec2_instance_info:
        region: "{{ ec2_region }}"
        filters:
          instance-state-name: running
          "tag:Workshop_splunk": "{{ec2_name_prefix}}-splunk"
      register: splunk_node_facts

    - name: ADD SPLUNK NODE TO INVENTORY
      add_host:
        name: "{{ item.tags.Name }}"
        short_name: "{{ item.tags.short_name }}"
        ansible_host: "{{ item.public_ip_address }}"
        username: "{{ item.tags.Student }}"
        ansible_user: "{{ item.tags.username }}"
        ansible_port: "{{ ssh_port }}"
        ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
        ansible_python_interpreter: "{{ec2_info['splunk_enterprise']['python_interpreter']}}"
        private_ip: "{{item.private_ip_address}}"
        groups:
          - security
          - security_connection_check
          - splunk
          - siem
      loop: "{{ splunk_node_facts.instances|flatten(levels=1) }}"

- name: MANAGE QRADAR EC2 INSTANCES (SECURITY MODE)
  when: security_console == 'qradar'
  block:
    - name: grab facts for qradarnode (SECURITY MODE)
      ec2_instance_info:
        region: "{{ ec2_region }}"
        filters:
          instance-state-name: running
          "tag:Workshop_qradar": "{{ec2_name_prefix}}-qradar"
      register: qradar_node_facts

    - name: ADD QRADAR NODE TO INVENTORY
      add_host:
        name: "{{ item.tags.Name }}"
        short_name: "{{ item.tags.short_name }}"
        ansible_host: "{{ item.public_ip_address }}"
        username: "{{ item.tags.Student }}"
        ansible_user: "{{ item.tags.username }}"
        ansible_port: "{{ ssh_port }}"
        ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
        ansible_python_interpreter: "{{ec2_info['qradar']['python_interpreter']}}"
        private_ip: "{{item.private_ip_address}}"
        groups:
          - security
          - security_connection_check
          - qradar
          - siem
      loop: "{{ qradar_node_facts.instances|flatten(levels=1) }}"

- name: MANAGE ATTACK SIMULATION EC2 INSTANCES (SECURITY MODE)
  block:
    - name: grab facts for attack simulation node (SECURITY MODE)
      ec2_instance_info:
        region: "{{ ec2_region }}"
        filters:
          instance-state-name: running
          "tag:Workshop_attacker": "{{ec2_name_prefix}}-attacker"
      register: attacker_node_facts

    - name: ADD ATTACK SIMULATION NODE TO INVENTORY
      add_host:
        name: "{{ item.tags.Name }}"
        short_name: "{{ item.tags.short_name }}"
        ansible_host: "{{ item.public_ip_address }}"
        username: "{{ item.tags.Student }}"
        ansible_user: "{{ item.tags.username }}"
        ansible_port: "{{ ssh_port }}"
        ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
        private_ip: "{{ item['network_interfaces']|map(attribute='private_ip_address')|list|ipaddr('172.16.0.0/16')|first }}"
        private_ip2: "{{ item['network_interfaces']|map(attribute='private_ip_address')|list|ipaddr('172.17.0.0/16')|first }}"
        groups:
          - security
          - security_connection_check
          - attack
      loop: "{{ attacker_node_facts.instances|flatten(levels=1) }}"

- name: grab facts for Check Point CloudGuard Security Management (SECURITY MODE)
  ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop_checkpoint_gw": "{{ec2_name_prefix}}-checkpoint"
  register: checkpoint_gw_facts

- name: MANAGE SNORT EC2 INSTANCES (SECURITY MODE)
  block:
    - name: grab facts for snort node (SECURITY MODE)
      ec2_instance_info:
        region: "{{ ec2_region }}"
        filters:
          instance-state-name: running
          "tag:Workshop_snort": "{{ec2_name_prefix}}-snort"
      register: snort_node_facts

    - name: ADD SNORT NODE TO INVENTORY
      add_host:
        name: "{{ item.tags.Name }}"
        short_name: "{{ item.tags.short_name }}"
        ansible_host: "{{ item.public_ip_address }}"
        username: "{{ item.tags.Student }}"
        ansible_user: "{{ item.tags.username }}"
        ansible_port: "{{ ssh_port }}"
        ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
        private_ip: "{{ item['network_interfaces']|map(attribute='private_ip_address')|list|ipaddr('172.16.0.0/16')|first }}"
        private_ip2: "{{ item['network_interfaces']|map(attribute='private_ip_address')|list|ipaddr('172.17.0.0/16')|first }}"
        groups:
          - security
          - security_connection_check
          - snort
          - ids
      loop: "{{ snort_node_facts.instances|flatten(levels=1) }}"

- name: MANAGE CHECK POINT EC2 INSTANCES (SECURITY MODE)
  block:
    - name: grab facts for Check Point CloudGuard Security Management (SECURITY MODE)
      ec2_instance_info:
        region: "{{ ec2_region }}"
        filters:
          instance-state-name: running
          "tag:Workshop_checkpoint_mgmt": "{{ec2_name_prefix}}-checkpoint"
      register: checkpoint_node_facts

    - name: ADD Check Point CloudGuard Security Management TO INVENTORY
      add_host:
        name: "{{ item.tags.Name }}"
        short_name: "{{ item.tags.short_name }}"
        ansible_host: "{{ item.public_ip_address }}"
        username: "{{ item.tags.Student }}"
        ansible_user: "{{ item.tags.username }}"
        ansible_port: "{{ ssh_port }}"
        ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
        private_ip: "{{item.private_ip_address}}"
        groups:
          - security
          - checkpoint
          - firewall
          - checkpoint_mgmt
      loop: "{{ checkpoint_node_facts.instances|flatten(levels=1) }}"

    - name: grab facts for Check Point NGFW (SECURITY MODE)
      ec2_instance_info:
        region: "{{ ec2_region }}"
        filters:
          instance-state-name: running
          "tag:Workshop_checkpoint_gw": "{{ec2_name_prefix}}-checkpoint"
      register: checkpoint_gw_node_facts

    - name: ADD Check Point NGFW TO INVENTORY
      add_host:
        name: "{{ item.tags.Name }}"
        short_name: "{{ item.tags.short_name }}"
        ansible_host: "{{ item.public_ip_address }}"
        username: "{{ item.tags.Student }}"
        ansible_user: "{{ item.tags.username }}"
        ansible_port: "{{ ssh_port }}"
        ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
        private_ip: "{{ item['network_interfaces']|map(attribute='private_ip_address')|list|ipaddr('172.16.0.0/16')|first }}"
        private_ip2: "{{ item['network_interfaces']|map(attribute='private_ip_address')|list|ipaddr('172.17.0.0/16')|first }}"
        groups:
          - security
          - checkpoint
          - firewall
      loop: "{{ checkpoint_gw_node_facts['instances']|flatten(levels=1) }}"

- name: MANAGE WINDOWS EC2 INSTANCES (SECURITY MODE)
  block:
    - name: grab facts for Windows workstation for Check Point (SECURITY MODE)
      ec2_instance_info:
        region: "{{ ec2_region }}"
        filters:
          instance-state-name: running
          "tag:Workshop_windows": "{{ec2_name_prefix}}-windows"
      register: windows_node_facts

    - name: ADD WINDOWS WORKSTATION TO INVENTORY
      add_host:
        name: "{{ item.tags.Name }}"
        short_name: "{{ item.tags.short_name }}"
        ansible_host: "{{ item.public_ip_address }}"
        ansible_user: Administrator
        ansible_password: "{{ windows_password }}"
        ansible_port: 5986
        ansible_connection: winrm
        ansible_winrm_server_cert_validation: ignore
        username: "{{ item.tags.Student }}"
        private_ip: "{{item.private_ip_address}}"
        groups:
          - security
          - windows
          - workstation
      loop: "{{ windows_node_facts.instances|flatten(levels=1) }}"

- name: Generate student inventories
  template:
    src: security_instances.txt.j2
    dest: "{{ playbook_dir }}/{{ec2_name_prefix}}/student{{item}}-instances.txt"
  with_sequence: count="{{ student_total }}"

- name: Generate student etchosts
  template:
    src: etchosts_security.j2
    dest: "{{ playbook_dir }}/{{ec2_name_prefix}}/student{{item}}-etchosts.txt"
  with_sequence: count="{{ student_total }}"

- name: Generate instructor inventory
  template:
    src: instructor_inventory_security.j2
    dest: "{{ playbook_dir }}/{{ec2_name_prefix}}/instructor_inventory.txt"
