---
# - name: WINDOWS | DomainController | find ami
#   ec2_ami_info:
#     region: "{{ ec2_region }}"
#     filters:
#       name: "{{ ec2_info['skylight_windows_dc']['filter'] }}"
#   register: amis

# - name: WINDOWS | DomainController| save ami
#   set_fact:
#     win_dc_ami: >
#       {{ amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}


- name: WINDOWS | GitLab | find ami
  ec2_ami_info:
    region: "{{ ec2_region }}"
    owners: "{{ ec2_info['skylight_rhel8_gitlab'].owners }}"
    filters:
      name: "{{ ec2_info['skylight_rhel8_gitlab']['filter'] }}"
      architecture: "{{ ec2_info['skylight_rhel8_gitlab'].architecture }}"
  register: amis

- name: WINDOWS | GitLab | save ami
  set_fact:
    win_gitlab_ami: >
      {{ amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}


# - name: WINDOWS | Docs | find ami
#   ec2_ami_info:
#     region: "{{ ec2_region }}"
#     filters:
#       name: "{{ ec2_info['skylight_rhel7_docs']['filter'] }}"
#   register: amis

# - name: WINDOWS | Docs | save ami
#   set_fact:
#     win_docs_ami: >
#       {{ amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}


- name: WINDOWS | Instance | find ami
  ec2_ami_info:
    region: "{{ ec2_region }}"
    filters:
      name: "{{ ec2_info['skylight_windows_instance']['filter'] }}"
  register: amis

- name: WINDOWS | Instance | save ami
  set_fact:
    win_instance_ami: >
      {{ amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}


# - name: WINDOWS | Workstation | find ami
#   ec2_ami_info:
#     region: "{{ ec2_region }}"
#     filters:
#       name: "{{ ec2_info['skylight_windows_ws']['filter'] }}"
#   register: amis

# - name: WINDOWS | Workstation | save ami
#   set_fact:
#     win_ws_ami: >
#       {{ amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}
