---
- name: Create EC2 instances for ansible node (control node)
  ec2:
    assign_public_ip: true
    key_name: "{{ ec2_name_prefix }}-key"
    group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_info[control_type].size }}"
    image: "{{ ansible_control_node_ami.image_id }}"
    region: "{{ ec2_region }}"
    exact_count: "{{ student_total }}"
    count_tag:
      Workshop_ansible: "{{ ec2_name_prefix }}-ansible-{{ sequence }}"
    instance_tags:
      Workshop_ansible: "{{ ec2_name_prefix }}-ansible-{{ sequence }}"
      Workshop: "{{ ec2_name_prefix }}"
      Workshop_type: "{{ workshop_type }}"
      AWS_USERNAME: "{{ aws_user }}"
      Info: "AWS_USERNAME that provisioned this-> {{ aws_user }}"
      Ansible_Workshops: "This was provisioned through the ansible workshops provisioner"
      Students: "{{ student_total }}"
      username: "{{ ec2_info[control_type].username }}"
      short_name: "ansible-{{ sequence }}"
      ansible-workshops: "true"
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ ec2_info[control_type].disk_space }}"
        delete_on_termination: true
  register: control_output

- name: Ensure tags are present
  ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{ item.1.id }}"
    state: present
    tags:
      Name: "{{ ec2_name_prefix }}-student{{ item.0 + 1 }}-ansible-{{ sequence }}"
      Index: "{{ item[0] }}"
      Student: "student{{item.0 + 1}}"
      dns: "{% if dns_type != 'none' %}student{{ item.0 + 1 }}.{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone }} {% else %} none {% endif %}"
      launch_time: "{{ item.1.launch_time }}"
  with_indexed_items:
    - "{{ control_output.instances }}"
  when: control_output.instance_ids is not none

- name: Grant AWS API access via IAM roles & policy block
  block:
    - name: Create VPC Lock Down role
      iam_role:
        name: "VPCLockDown_{{ ec2_name_prefix }}"
        assume_role_policy_document: "{{ lookup('file','AssumeRole_policy.json') }}"
        create_instance_profile: yes
        description: VPC Lockdown role for "{{ ec2_name_prefix }}" workshop

    - name: set fact for VPC Lock Down role used for all automated nodes
      set_fact:
        node_ec2_instance_role_name: "VPCLockDown_{{ ec2_name_prefix }}"

    - name: Create control node instance role
      iam_role:
        name: "ControlNode_{{ ec2_name_prefix }}_student{{ item }}"
        assume_role_policy_document: "{{ lookup('file','AssumeRole_policy.json') }}"
        create_instance_profile: yes
        description: Control node instance role for "{{ ec2_name_prefix }}" workshop
      loop: "{{ range(1, student_total + 1)|list }}"

    - name: Generate IAM policy for control node IAM instance role
      iam_policy:
        iam_type: role
        iam_name: "ControlNode_{{ ec2_name_prefix }}_student{{ item }}" 
        policy_name: "IAMPolicy_{{ ec2_name_prefix }}_student{{ item }}"
        state: present
        policy_json: "{{ lookup( 'template', 'iam_vpc_lockdown_policy.json.j2') }}"
      loop: "{{ range(1, student_total + 1)|list }}"
      loop_control:
        index_var: loop_idx

    - name: Associate IAM instance profile with control node
      command: >
        aws ec2 associate-iam-instance-profile
          --iam-instance-profile Name=ControlNode_{{ ec2_name_prefix }}_student{{ item.0 + 1 }}
          --instance-id {{ item.1.id }}
          --region {{ ec2_region }}
      with_indexed_items:
        - "{{ control_output.instances }}"
      register: associate_iam_instance_profile
      when: control_output.instance_ids is not none

    - name: Check associate_iam_instance_profile 
      debug:
        msg: "{{ associate_iam_instance_profile }}"
      when: control_output.instance_ids is not none

  when: tower_node_aws_api_access|bool
