- name: grab facts for control_nodes
  ec2_instance_facts:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop_ansible": "{{ec2_name_prefix}}-ansible"
  register: ansible_node_facts

- name: DEBUG ansible_node_facts
  debug:
    var: ansible_node_facts

- name: add ansible node to control_nodes and managed_nodes group
  add_host:
    name: "{{ item.tags.Name }}"
    username: "{{ item.tags.Student }}"
    student: "{{ item.tags.Student }}"
    short_name: "{{ item.tags.short_name }}"
    ansible_host: "{{ item.public_ip_address }}"
    ansible_user: "{{ ec2_login_names[ansible_node] }}"
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    private_ip: "{{item.private_ip_address}}"
    groups:
      - managed_nodes
      - control_nodes
  with_items: "{{ ansible_node_facts.instances }}"

- name: engine (essentials) mode - setup inventory
  include_tasks: "addhost_engine.yml"
  when:
    - not networking
    - not f5workshop

- name: networking mode - setup inventory
  include_tasks: "addhost_networking.yml"
  when:
    - networking
    - not f5workshop

- name: f5 mode - setup inventory
  include_tasks: "addhost_f5.yml"
  when: f5workshop
