---
- name: grab facts for control_nodes
  ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop_ansible": "{{ec2_name_prefix}}-ansible*"
  register: ansible_node_facts

- name: add ansible node to control_nodes and managed_nodes group
  add_host:
    name: "{{ item.tags.Name }}"
    username: "{{ item.tags.Student }}"
    student: "{{ item.tags.Student }}"
    short_name: "{{ item.tags.short_name }}"
    ansible_host: "{{ item.public_ip_address }}"
    ansible_user: "{{ item.tags.username }}"
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    private_ip: "{{item.private_ip_address}}"
    groups:
      - control_nodes
  with_items: "{{ ansible_node_facts.instances }}"

- name: setup inventory
  include_tasks: "inventory/addhost_{{workshop_type}}.yml"

################### Write inventories ##################
- name: Generate student inventories
  template:
    src: "student_inventory/instances_{{workshop_type}}.j2"
    dest: "{{ playbook_dir }}/{{ec2_name_prefix}}/student{{item}}-instances.txt"
  with_sequence: count="{{ student_total }}"

- name: Generate student etchosts
  template:
    src: "etchosts/etchosts_{{workshop_type}}.j2"
    dest: "{{ playbook_dir }}/{{ec2_name_prefix}}/student{{item}}-etchosts.txt"
  with_sequence: count="{{ student_total }}"

- name: Generate instructor inventory
  template:
    src: "instructor_inventory/instructor_inventory_{{workshop_type}}.j2"
    dest: "{{ playbook_dir }}/{{ec2_name_prefix}}/instructor_inventory.txt"
