---
- name: Install EPEL for python2-pip
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    state: present

- name: make sure pip is installed
  yum:
    name: python2-pip
    state: present

- name: install ansible-tower-cli and requests
  pip:
    name:
      - ansible-tower-cli
      - "requests==2.6.0"
    state: latest

- name: CHANGE TOWER BASE URL
  tower_settings:
    name: TOWER_URL_BASE
    value: "https://{{ record }}"
    tower_verify_ssl: false
    tower_host: "{{ record }}"
    tower_username: admin
    tower_password: "{{admin_password}}"
  #delegate_to: "{{username}}.ansible.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"

- name: Install EPEL
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    state: present

- name: INSTALL CERTBOT
  yum:
    name: certbot

# https://docs.ansible.com/ansible-tower/latest/html/administration/init_script.html
- name: TURN OFF TOWER
  shell: ansible-tower-service stop

# If this fails check out status of certbot: https://letsencrypt.status.io/
- name: ISSUE CERT
  shell: certbot certonly --standalone -d {{ record }} --email ansible-network@redhat.com --noninteractive --agree-tos
  register: issue_cert
  until: issue_cert is not failed
  retries: 5
  ignore_errors: true

- name: APPEND LETS ENCRYPT FAILED
  set_fact:
    dns_information: |
      - The Lets Encrypt certbot failed, please check https://letsencrypt.status.io/ to make sure the service is running
  run_once: true
  delegate_to: localhost
  delegate_facts: true
  when: issue_cert is failed

- name: If issue cert works install it on tower
  block:
    - name: MOVE SSL KEY
      copy:
        remote_src: true
        src: "/etc/letsencrypt/live/{{ record }}/privkey.pem"
        dest: /etc/tower/tower.key

    - name: GRAB SPECIFIC SSL CERT
      slurp:
        src: "/etc/letsencrypt/live/{{ record }}/cert.pem"
      register: intermediate_cert

    - name: COMBINE SPECIFIC AND INTERMEDIATE CERT
      template:
        src: combined_cert.j2
        dest: /etc/tower/tower.cert
  when: issue_cert is not failed

- name: TURN ON TOWER
  shell: ansible-tower-service start
  register: install_tower
  until: install_tower is not failed
  retries: 5
