---
- name: find ami for node1
  ec2_ami_info:
    region: "{{ ec2_region }}"
    owners: "{{ ec2_info[rhel].owners }}"
    filters:
      name: "{{ ec2_info[rhel].filter }}"
      architecture: "{{ ec2_info[rhel].architecture }}"
  register: amis

- name: save ami for node1
  set_fact:
    node1_ami: >
      {{ amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}

- name: Create EC2 instances for node1
  ec2:
    assign_public_ip: true
    key_name: "{{ ec2_name_prefix }}-key"
    group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_info[rhel].size }}"
    image: "{{ node1_ami.image_id }}"
    region: "{{ ec2_region }}"
    exact_count: "{{ student_total }}"
    count_tag:
      Workshop_node1: "{{ ec2_name_prefix }}-node1"
    instance_tags:
      Workshop_node1: "{{ ec2_name_prefix }}-node1"
      Workshop_type: "{{ workshop_type }}"
      Workshop: "{{ ec2_name_prefix }}"
      AWS_USERNAME: "{{ aws_user }}"
      Info: "AWS_USERNAME that provisioned this-> {{ aws_user }}"
      Linklight: "This was provisioned through the linklight provisioner"
      Students: "{{ student_total }}"
      short_name: "dev_web1"
      username: "{{ ec2_info[rhel].username }}"
      Devops_tag: dev_web1
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ ec2_info[rhel].disk_space }}"
        delete_on_termination: true
  register: node1_output

- name: Ensure tags are present for node1
  ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{ item.1 }}"
    state: present
    tags:
      Name: "{{ ec2_name_prefix }}-student{{ item.0 + 1 }}-node1"
      Index: "{{ item[0] }}"
      Student: "student{{ item.0 + 1 }}"
      launch_time: "{{ item.1.launch_time }}"
  with_indexed_items:
    - "{{ node1_output.instance_ids }}"
  when: node1_output.instance_ids is not none

- name: find ami for node2
  ec2_ami_info:
    region: "{{ ec2_region }}"
    owners: "{{ ec2_info[rhel].owners }}"
    filters:
      name: "{{ ec2_info[rhel].filter }}"
      architecture: "{{ ec2_info[rhel].architecture }}"
  register: amis

- name: save ami for node2
  set_fact:
    node2_ami: >
      {{ amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}

- name: Create EC2 instances for node2
  ec2:
    assign_public_ip: true
    key_name: "{{ ec2_name_prefix }}-key"
    group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_info[rhel].size }}"
    image: "{{ node2_ami.image_id }}"
    region: "{{ ec2_region }}"
    exact_count: "{{ student_total }}"
    count_tag:
      Workshop_node2: "{{ ec2_name_prefix }}-node2"
    instance_tags:
      Workshop_node2: "{{ ec2_name_prefix }}-node2"
      Workshop_type: "{{ workshop_type }}"
      Workshop: "{{ ec2_name_prefix }}"
      AWS_USERNAME: "{{ aws_user }}"
      Info: "AWS_USERNAME that provisioned this-> {{ aws_user }}"
      Linklight: "This was provisioned through the linklight provisioner"
      Students: "{{ student_total }}"
      short_name: "dev_web2"
      username: "{{ ec2_info[rhel].username }}"
      Devops_tag: dev_web2
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ ec2_info[rhel].disk_space }}"
        delete_on_termination: true
  register: node2_output

- name: Ensure tags are present for node2
  ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{ item.1 }}"
    state: present
    tags:
      Name: "{{ ec2_name_prefix }}-student{{ item.0 + 1 }}-node2"
      Index: "{{ item[0] }}"
      Student: "student{{ item.0 + 1 }}"
      launch_time: "{{ item.1.launch_time }}"
  with_indexed_items:
    - "{{ node2_output.instance_ids }}"
  when: node2_output.instance_ids is not none

- name: find ami for node3
  ec2_ami_info:
    region: "{{ ec2_region }}"
    owners: "{{ ec2_info[rhel].owners }}"
    filters:
      name: "{{ ec2_info[rhel].filter }}"
      architecture: "{{ ec2_info[rhel].architecture }}"
  register: amis

- name: save ami for node3
  set_fact:
    node3_ami: >
      {{ amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}

- name: Create EC2 instances for node3
  ec2:
    assign_public_ip: true
    key_name: "{{ ec2_name_prefix }}-key"
    group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_info[rhel].size }}"
    image: "{{ node3_ami.image_id }}"
    region: "{{ ec2_region }}"
    exact_count: "{{ student_total }}"
    count_tag:
      Workshop_node3: "{{ ec2_name_prefix }}-node3"
    instance_tags:
      Workshop_node3: "{{ ec2_name_prefix }}-node3"
      Workshop_type: "{{ workshop_type }}"
      Workshop: "{{ ec2_name_prefix }}"
      AWS_USERNAME: "{{ aws_user }}"
      Info: "AWS_USERNAME that provisioned this-> {{ aws_user }}"
      Linklight: "This was provisioned through the linklight provisioner"
      Students: "{{ student_total }}"
      short_name: "prod_web1"
      username: "{{ ec2_info[rhel].username }}"
      Devops_tag: prod_web1
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ ec2_info[rhel].disk_space }}"
        delete_on_termination: true
  register: node3_output

- name: Ensure tags are present for node3
  ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{ item.1 }}"
    state: present
    tags:
      Name: "{{ ec2_name_prefix }}-student{{ item.0 + 1 }}-node3"
      Index: "{{ item[0] }}"
      Student: "student{{ item.0 + 1 }}"
      launch_time: "{{ item.1.launch_time }}"
  with_indexed_items:
    - "{{ node3_output.instance_ids }}"
  when: node3_output.instance_ids is not none

- name: find ami for node4
  ec2_ami_info:
    region: "{{ ec2_region }}"
    owners: "{{ ec2_info[rhel].owners }}"
    filters:
      name: "{{ ec2_info[rhel].filter }}"
      architecture: "{{ ec2_info[rhel].architecture }}"
  register: amis

- name: save ami for node4
  set_fact:
    node4_ami: >
      {{ amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}

- name: Create EC2 instances for node4
  ec2:
    assign_public_ip: true
    key_name: "{{ ec2_name_prefix }}-key"
    group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_info[rhel].size }}"
    image: "{{ node4_ami.image_id }}"
    region: "{{ ec2_region }}"
    exact_count: "{{ student_total }}"
    count_tag:
      Workshop_node4: "{{ ec2_name_prefix }}-node4"
    instance_tags:
      Workshop_node4: "{{ ec2_name_prefix }}-node4"
      Workshop_type: "{{ workshop_type }}"
      Workshop: "{{ ec2_name_prefix }}"
      AWS_USERNAME: "{{ aws_user }}"
      Info: "AWS_USERNAME that provisioned this-> {{ aws_user }}"
      Linklight: "This was provisioned through the linklight provisioner"
      Students: "{{ student_total }}"
      short_name: "prod_web2"
      username: "{{ ec2_info[rhel].username }}"
      Devops_tag: prod_web2
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ ec2_info[rhel].disk_space }}"
        delete_on_termination: true
  register: node4_output

- name: Ensure tags are present for node4
  ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{ item.1 }}"
    state: present
    tags:
      Name: "{{ ec2_name_prefix }}-student{{ item.0 + 1 }}-node4"
      Index: "{{ item[0] }}"
      Student: "student{{ item.0 + 1 }}"
      launch_time: "{{ item.1.launch_time }}"
  with_indexed_items:
    - "{{ node4_output.instance_ids }}"
  when: node4_output.instance_ids is not none
