---
- name: login, get SID
  uri:
    url: "https://{{ hostvars[inventory_hostname|regex_replace('ansible', 'checkpoint_mgmt')]['private_ip'] }}/web_api/login"
    method: POST
    body:
      user: admin
      password: admin123
    body_format: json
    validate_certs: false
  register: login_data
  until: (login_data.status == 200) and (login_data.json is defined)
  retries: 30
  delay: 10

- name: Add NGFW to MGMT
  uri:
    url: "https://{{ hostvars[inventory_hostname|regex_replace('ansible', 'checkpoint_mgmt')]['private_ip'] }}/web_api/add-simple-gateway"
    validate_certs: false
    method: POST
    headers:
      Content-Type: application/json
      X-chkp-sid: "{{ login_data.json.sid }}"
    body_format: json
    body:
      name: myngfw
      ip-address: "{{ hostvars[inventory_hostname|regex_replace('ansible', 'checkpoint_gw')]['private_ip'] }}"
      one-time-password: admin123
      firewall: true
      version: R80.30
      os-name: Gaia
      interfaces:
        - anti-spoofing: true
          anti-spoofing-settings:
            action: prevent
          name: "eth0"
          ip-address: "{{ hostvars[inventory_hostname|regex_replace('ansible', 'checkpoint_gw')]['private_ip'] }}"
          network-mask: "255.255.0.0"
          ipv4-mask-length: 16
          security-zone: false
          topology: internal
          topology-settings:
            ip-address-behind-this-interface: "network defined by the interface ip and net mask"
        - anti-spoofing: true
          anti-spoofing-settings:
            action: prevent
          name: "eth1"
          ip-address: "{{ hostvars[inventory_hostname|regex_replace('ansible', 'checkpoint_gw')]['private_ip2'] }}"
          network-mask: "255.255.0.0"
          ipv4-mask-length: 16
          security-zone: false
          topology: external

- name: Publish
  uri:
    url: "https://{{ hostvars[inventory_hostname|regex_replace('ansible', 'checkpoint_mgmt')]['private_ip'] }}/web_api/publish"
    validate_certs: false
    method: POST
    headers:
      Content-Type: application/json
      X-chkp-sid: "{{ login_data.json.sid }}"
    body_format: json
    body: >
      {}

- name: get gw instances
  ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      "tag:Name": "{{ inventory_hostname|regex_replace('ansible', 'checkpoint_gw') }}"
      "instance-state-name": running
  register: gw_inst
  delegate_to: localhost

- name: disable source_dest_checking on AWS interface
  ec2_eni:
    region: "{{ ec2_region }}"
    eni_id: "{{ gw_inst['instances'][0]['network_interfaces'][0]['network_interface_id'] if gw_inst['instances'][0]['network_interfaces'][0]['attachment']['device_index'] == 1 else gw_inst['instances'][0]['network_interfaces'][1]['network_interface_id'] }}"
    source_dest_check: false
    state: present
  delegate_to: localhost
