ec2_region: eu-central-1
ec2_az: eu-central-1a
ec2_name_prefix: demo
student_total: 1                      # amount of work benches to provision
## Optional Variables
admin_password: ansible               # password used for student account on control node
localsecurity: false                  # skips firewalld installation and SE Linux when false
create_login_page: true               # creates HTML website for workshop
networking: true                      # workshop is put into networking mode, uses two Cisco IOS-XE devices
autolicense: true                     # when towerinstall is on, this will license it with provided license
towerinstall: true                    # this will install Ansible Tower on all control nodes
f5workshop: true                      # workshp runs in F5 mode
