---
argument_specs:
  main:
    short_description: General configuration for the control node.
    options:
      f5_ee:
        type: str
        description: f5 workshop execution environment
        default: "quay.io/acme_corp/f5_ee:latest"
      security_ee:
        type: str
        description: security workshop execution environment
        default: "quay.io/acme_corp/security_ee:latest"
      rhel_ee:
        type: str
        description: rhel workshop execution environment
        default: "registry.redhat.io/ansible-automation-platform-20-early-access/ee-supported-rhel8:2.0.0"
      network_ee:
        type: str
        description: network workshop execution environment
        default: "registry.redhat.io/ansible-automation-platform-20-early-access/ee-supported-rhel8:2.0.0"
      rhel_90_ee:
        type: str
        description: rhel_90 workshop execution environment
        default: "registry.redhat.io/ansible-automation-platform-20-early-access/ee-supported-rhel8:2.0.0"
      windows_ee:
        type: str
        description: windows workshop execution environment
        default: "registry.redhat.io/ansible-automation-platform-20-early-access/ee-supported-rhel8:2.0.0"
      smart_mgmt_ee:
        type: str
        description: smart_mgmt workshop execution environment
        default: "quay.io/s4v0/ee-automated-smart-mgmt-29:1.0.3"
      username:
        description: The workshop username.
        type: str
        required: true
      ec2_name_prefix:
        description: A prefix for EC2 and DNS resources.
        type: str
        required: true
      ansible_workshops_url:
        description: The repository url for ansible/workshops.
        type: str
        required: false
      ansible_workshops_version:
        description: The repository version for ansible/workshops.
        type: str
        required: false
      ansible_workshops_refspec:
        description: The repository refspec for ansible/workshops.
        type: str
        required: false
      exercise_src_location:
        description: The location of the exercise in ansible/workshops.
        type: str
        required: false
      workshop_type:
        description: The type of the workshop.
        type: str
        required: true
      admin_password:
        description: The Ansible Tower admin password.
        type: str
        required: true
      controllerinstall:
        description: Whether to install automation controller.
        type: bool
        required: false
        default: false
      tower_node_aws_api_access:
        description: Whether Ansible controller has access ot the AWS API.
        type: bool
        required: false
        default: false
  devops:
    short_description: Configure the devops workshop.
    options:
      username:
        description: The workshop username.
        type: str
        required: true
  f5:
    short_description: Configure the F5 workshop.
    options:
      username:
        description: The workshop username.
        type: str
        required: true
  network:
    short_description: Configure the network workshop.
  package_dependencies:
    short_description: Install general package dependencies for workshops.
  route53_update:
    short_description: Configure the Route53 update service.
    options:
      username:
        description: The workshop username.
        type: str
        required: true
  security:
    short_description: Configure the security workshop
  tower:
    short_description: Configure Ansible Controller.
    options:
      default_platform_url:
        description: The default URL to the Ansible Platform .tar.gz installer.
        type: str
        required: true
      admin_password:
        description: The automation controller admin password.
        type: str
        required: true
      tower_license:
        description: The tower license file contents.
        type: str
        required: true
      create_cluster:
        description: Whether to create an automation controller cluster.
        type: bool
        required: true
      gpgcheck:
        description: Whether to perform GPG checking on repository packages.
        type: int
        required: false
        default: 0
        choices:
          - 0
          - 1
      aw_repo_url:
        description: The repository URL for Ansible Tower installation.
        type: str
        required: false
        default: https://releases.ansible.com/ansible-tower/
  unsupported_workshop:
    short_description: Catch-all for unsupported workshop types.
    options:
      workshop_type:
        description: The type of the workshop.
        type: str
        required: true
  venv:
    short_description: Set up a virtual environment for Ansible Tower.
    options:
      admin_password:
        description: The Ansible Tower admin password.
        type: str
        required: true
  windows:
    short_description: Set up Windows workshop prerequisites.
