---
# These are the default variables common to most tower_configuration and _utilities roles
# You shouldn't need to define them again and again but they should be defined
#tower_hostname: "{{ inventory_hostname }}"
#tower_username: "admin"
#tower_password: ""
#tower_oauthtoken: ""
#tower_config_file: ""
#tower_validate_certs: false

# These are the default variables specific to the license role

# list of dict describing Tower schedules:
tower_schedules:
# possible fields:
#- name: "schedule_name"  # mandatory
#  new_name: "new_name"  # optional
#  description: "some description"  # optional
#  rrule: "DTSTART:20191219T130551Z RRULE:FREQ=WEEKLY;INTERVAL=1;COUNT=1"  # optional, iCal recurrence rule
#  extra_data: {}  # optional, extra vars for template
#  inventory: "inventory_name"  # optional, job template must prompt for inventory
#  scm_branch:  # optional, str
#  job_type:  # optional, choices: run, check
#  job_tags: "tag1,tag2"  # optional, comma separated list of tags
#  skip_tags: "tag3,tag4"  # optional, comma separated list of tags
#  limit:  # optional, str
#  diff_mode: false  # optional, boolean
#  verbosity: 0  # optional, choices: [0-5]
#  unified_job_template: "job_template_name"  # optional, str
#  enabled: true  # optional, boolean
#  state: present  # optional, choices: present, absent

tower_configuration_schedules_secure_logging: "{{tower_configuration_secure_logging | default(false)}}"
