- name: grab facts for control_nodes
  ec2_instance_facts:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop_ansible": "{{ec2_name_prefix}}-ansible"
  register: ansible_node_facts

- name: add ansible node to control_nodes group
  add_host:
    name: "{{ item.tags.Name }}"
    short_name: "{{ item.tags.short_name }}"
    ansible_host: "{{ item.public_ip_address }}"
    ansible_user: "{{ ec2_login_names[ansible_node] }}"
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    private_ip: "{{item.private_ip_address}}"
    groups:
      - lab_hosts
      - control_nodes
  with_items: "{{ ansible_node_facts.instances }}"

- name: engine (essentials) mode - setup inventory
  include_tasks: "addhost_engine.yml"
  when:
    - not networking

- name: networking mode - setup inventory
  include_tasks: "addhost_networking.yml"
  when:
    - networking is defined
    - networking

# - name: debug what this next task is doing
#   debug:
#     msg: "{{item}}"
#   with_items: "{{ groups.lab_hosts }}"
#   delegate_to: "{{ item }}"
#   delegate_facts: yes

- name: Set local username to create on instances
  set_fact:
    username: "{{ item | regex_replace('.*-(\\w*)-\\w*$','\\1') }}"
  with_items: "{{ groups.lab_hosts }}"
  delegate_to: "{{ item }}"
  delegate_facts: yes

- name: Generate student inventories
  template:
    src: "{{ networking | ternary( 'networking_instances.txt.j2' , 'instances.txt.j2' ) }}"
    dest: "{{ playbook_dir }}/{{ec2_name_prefix}}/student{{item}}-instances.txt"
  with_sequence: count="{{ student_total }}"

- name: Generate student etchosts
  template:
    src: etchosts_networking.j2
    dest: "{{ playbook_dir }}/{{ec2_name_prefix}}/student{{item}}-etchosts.txt"
  with_sequence: count="{{ student_total }}"
  when: networking

- name: Generate instructor inventory
  template:
    src: "{{ networking | ternary( 'instructor_inventory_networking.j2' , 'instructor_inventory.j2' ) }}"
    dest: "{{ playbook_dir }}/{{ec2_name_prefix}}/instructor_inventory.txt"
