---
- name: Playbook to configure execution environments
  hosts: builder
  gather_facts: true
  vars_files:
    - "../vault.yml"
  tasks:
    - name: Include ee_builder role
      ansible.builtin.include_role:
        name: infra.ee_utilities.ee_builder
...
