---
- name: make sure we have access to pre_build AMI
  block:
    - name: check if we have access to AMI
      amazon.aws.ec2_ami_info:
        region: "{{ ec2_region }}"
        image_ids: "{{ pre_build_controller_ami[ec2_region] }}"
  rescue:
    - name: AWS AMI Access is not available
      fail:
        msg: "You do not have access to the pre_build AMI for region {{ ec2_region }}.  Please re-run with pre_build set to false"
